// Code generated by `aru view:build` from login.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package auth

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/auth/login.kyse.go:11

// LoginData is what the sign-in screen draws.
type LoginData = authui.AuthPage

//line resources/views/auth/login.go:22

func init() { view.Register("auth.login", renderAuthLogin) }

// renderAuthLogin renders auth.login.
func renderAuthLogin(w io.Writer, data any) error {
	d, ok := data.(LoginData)
	if !ok {
		return view.WrongData("auth.login", "LoginData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<section class=\"card\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<header class=\"border-b px-6 py-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<h1 class=\"text-base font-semibold tracking-tight\">Login</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<form class=\"flex flex-col gap-4 px-6 py-6\" method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:28
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginURL)))
//line resources/views/auth/login.go:60
			}
			if err == nil {
				_, err = io.WriteString(w, "\"\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\thx-post=\"")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:29
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginURL)))
//line resources/views/auth/login.go:71
			}
			if err == nil {
				_, err = io.WriteString(w, "\" hx-target=\"this\" hx-swap=\"outerHTML\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:32
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "email", Label: "Email", Type: "email", Value: d.Email, Error: d.EmailError, Autocomplete: "username", Required: true, Autofocus: true})))
//line resources/views/auth/login.go:88
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:38
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "password", Label: "Password", Type: "password", Error: d.PasswordError, Autocomplete: "current-password", Required: true})))
//line resources/views/auth/login.go:102
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<label class=\"flex items-center gap-2 text-sm\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<input class=\"input\" type=\"checkbox\" name=\"remember\" value=\"1\" ")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:45
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RememberAttribute())))
//line resources/views/auth/login.go:119
			}
			if err == nil {
				_, err = io.WriteString(w, ">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\tRemember me\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<div class=\"flex items-center justify-between gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<button type=\"submit\" class=\"btn\">Login</button>\n")
			}
//line resources/views/auth/login.kyse.go:51
			if d.HasPasswordReset {
//line resources/views/auth/login.go:141
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t<a class=\"text-muted-foreground text-sm hover:underline\" href=\"")
				}
				if err == nil {
//line resources/views/auth/login.kyse.go:52
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordRequestURL)))
//line resources/views/auth/login.go:148
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Forgot your password?</a>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
