// Code generated by `aru view:build` from register.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package auth

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/auth/register.kyse.go:11

// RegisterData is what the sign-up screen draws.
type RegisterData = authui.AuthPage

//line resources/views/auth/register.go:22

func init() { view.Register("auth.register", renderAuthRegister) }

// renderAuthRegister renders auth.register.
func renderAuthRegister(w io.Writer, data any) error {
	d, ok := data.(RegisterData)
	if !ok {
		return view.WrongData("auth.register", "RegisterData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<section class=\"card\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<header class=\"border-b px-6 py-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<h1 class=\"text-base font-semibold tracking-tight\">Register</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<form class=\"flex flex-col gap-4 px-6 py-6\" method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/register.kyse.go:25
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RegisterURL)))
//line resources/views/auth/register.go:60
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/register.kyse.go:28
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "name", Label: "Name", Value: d.Name, Error: d.NameError, Autocomplete: "name", Required: true, Autofocus: true})))
//line resources/views/auth/register.go:77
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/register.kyse.go:34
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "email", Label: "Email", Type: "email", Value: d.Email, Error: d.EmailError, Autocomplete: "email", Required: true})))
//line resources/views/auth/register.go:91
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/register.kyse.go:40
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "password", Label: "Password", Type: "password", Error: d.PasswordError, Hint: "At least twelve characters.", Autocomplete: "new-password", Required: true})))
//line resources/views/auth/register.go:105
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/register.kyse.go:47
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "password_confirmation", Label: "Confirm password", Type: "password", Error: d.PasswordConfirmationError, Autocomplete: "new-password", Required: true})))
//line resources/views/auth/register.go:119
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<div class=\"flex items-center justify-between gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<button type=\"submit\" class=\"btn\">Register</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<a class=\"text-muted-foreground text-sm hover:underline\" href=\"")
			}
			if err == nil {
//line resources/views/auth/register.kyse.go:55
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginURL)))
//line resources/views/auth/register.go:139
			}
			if err == nil {
				_, err = io.WriteString(w, "\">Already registered?</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
