// Code generated by `aru view:build` from verify.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package auth

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/auth/verify.kyse.go:11

// VerifyData is what the verification notice draws.
type VerifyData = authui.AuthPage

//line resources/views/auth/verify.go:22

func init() { view.Register("auth.verify", renderAuthVerify) }

// renderAuthVerify renders auth.verify.
func renderAuthVerify(w io.Writer, data any) error {
	d, ok := data.(VerifyData)
	if !ok {
		return view.WrongData("auth.verify", "VerifyData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<section class=\"card\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<header class=\"border-b px-6 py-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<h1 class=\"text-base font-semibold tracking-tight\">Verify your email</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<div class=\"flex flex-col gap-4 px-6 py-6 text-sm\">\n")
			}
//line resources/views/auth/verify.kyse.go:26
			if d.Resent {
//line resources/views/auth/verify.go:59
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t")
				}
				if err == nil {
//line resources/views/auth/verify.kyse.go:27
					_, err = io.WriteString(w, view.Text(components.Alert(components.AlertProps{Title: "A fresh link is on its way", Message: "Check the address you registered with."})))
//line resources/views/auth/verify.go:66
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<p class=\"text-muted-foreground\">Before going on, follow the link we sent you. If it did not arrive, ask for another.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<form method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/verify.kyse.go:35
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.VerificationResendURL)))
//line resources/views/auth/verify.go:87
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<button type=\"submit\" class=\"btn\">Send it again</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
