// Code generated by `aru view:build` from login.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

func init() { view.Register("auth.login", renderAuthLogin) }

// renderAuthLogin renders auth.login.
func renderAuthLogin(w io.Writer, data any) error {
	d, ok := data.(AuthPage)
	if !ok {
		return view.WrongData("auth.login", "AuthPage", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<section class=\"overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<h1 class=\"border-b border-slate-200 px-6 py-4 text-base font-semibold tracking-tight dark:border-slate-800\">Login</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<!-- hx-target and hx-swap on the form itself: a rejected login answers 422 with\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "     this same fragment, and it has to replace itself. Swapping it in anywhere\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "     else would leave the old form on the page, with the token that was just\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "     spent -- and the second attempt fails a CSRF check nobody can see. -->\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<form method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:15
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginURL)))
//line resources/views/auth_login.go:54
			}
			if err == nil {
				_, err = io.WriteString(w, "\" hx-post=\"")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:15
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginURL)))
//line resources/views/auth_login.go:62
			}
			if err == nil {
				_, err = io.WriteString(w, "\" hx-target=\"this\" hx-swap=\"outerHTML\" class=\"space-y-5 px-6 py-6\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<label for=\"email\" class=\"block text-sm font-medium text-slate-700 dark:text-slate-200\">Email address</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<input id=\"email\" name=\"email\" type=\"email\" value=\"")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:19
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Email)))
//line resources/views/auth_login.go:82
			}
			if err == nil {
				_, err = io.WriteString(w, "\" required autofocus autocomplete=\"email\" class=\"mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 shadow-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:focus:border-slate-100\">\n")
			}
//line resources/views/auth/login.kyse.go:20
			if d.EmailError != "" {
//line resources/views/auth_login.go:89
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"alert\" class=\"mt-2 text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/auth/login.kyse.go:21
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.EmailError)))
//line resources/views/auth_login.go:96
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<label for=\"password\" class=\"block text-sm font-medium text-slate-700 dark:text-slate-200\">Password</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<input id=\"password\" name=\"password\" type=\"password\" required autocomplete=\"current-password\" class=\"mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 shadow-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:focus:border-slate-100\">\n")
			}
//line resources/views/auth/login.kyse.go:27
			if d.PasswordError != "" {
//line resources/views/auth_login.go:116
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"alert\" class=\"mt-2 text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/auth/login.kyse.go:28
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordError)))
//line resources/views/auth_login.go:123
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"flex items-center gap-2\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<input id=\"remember\" name=\"remember\" type=\"checkbox\" value=\"1\" ")
			}
			if err == nil {
//line resources/views/auth/login.kyse.go:32
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RememberAttribute())))
//line resources/views/auth_login.go:141
			}
			if err == nil {
				_, err = io.WriteString(w, " class=\"size-4 rounded border-slate-300 text-slate-900 focus:ring-2 focus:ring-slate-900/20 dark:border-slate-700 dark:bg-slate-950\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<label for=\"remember\" class=\"text-sm text-slate-600 dark:text-slate-300\">Remember me</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"flex items-center justify-between gap-4 pt-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<button type=\"submit\" class=\"inline-flex items-center justify-center rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-900/20 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-white\">Login</button>\n")
			}
//line resources/views/auth/login.kyse.go:37
			if d.HasPasswordReset {
//line resources/views/auth_login.go:160
				if err == nil {
					_, err = io.WriteString(w, "<a href=\"")
				}
				if err == nil {
//line resources/views/auth/login.kyse.go:38
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordRequestURL)))
//line resources/views/auth_login.go:167
				}
				if err == nil {
					_, err = io.WriteString(w, "\" class=\"text-sm font-medium text-slate-600 underline underline-offset-4 hover:text-slate-900 dark:text-slate-300 dark:hover:text-slate-100\">Forgot your password?</a>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
