// Code generated by `aru view:build` from reset.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

func init() { view.Register("auth.passwords.reset", renderAuthPasswordsReset) }

// renderAuthPasswordsReset renders auth.passwords.reset.
func renderAuthPasswordsReset(w io.Writer, data any) error {
	d, ok := data.(AuthPage)
	if !ok {
		return view.WrongData("auth.passwords.reset", "AuthPage", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<section class=\"overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<h1 class=\"border-b border-slate-200 px-6 py-4 text-base font-semibold tracking-tight dark:border-slate-800\">Reset password</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<form method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:11
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordUpdateURL)))
//line resources/views/auth_passwords_reset.go:42
			}
			if err == nil {
				_, err = io.WriteString(w, "\" class=\"space-y-5 px-6 py-6\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "<input type=\"hidden\" name=\"token\" value=\"")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:13
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.ResetToken)))
//line resources/views/auth_passwords_reset.go:56
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<label for=\"email\" class=\"block text-sm font-medium text-slate-700 dark:text-slate-200\">Email address</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<input id=\"email\" name=\"email\" type=\"email\" value=\"")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:16
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Email)))
//line resources/views/auth_passwords_reset.go:73
			}
			if err == nil {
				_, err = io.WriteString(w, "\" required autofocus autocomplete=\"email\" class=\"mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 shadow-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:focus:border-slate-100\">\n")
			}
//line resources/views/auth/passwords/reset.kyse.go:17
			if d.EmailError != "" {
//line resources/views/auth_passwords_reset.go:80
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"alert\" class=\"mt-2 text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:18
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.EmailError)))
//line resources/views/auth_passwords_reset.go:87
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<label for=\"password\" class=\"block text-sm font-medium text-slate-700 dark:text-slate-200\">Password</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<input id=\"password\" name=\"password\" type=\"password\" required autocomplete=\"new-password\" class=\"mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 shadow-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:focus:border-slate-100\">\n")
			}
//line resources/views/auth/passwords/reset.kyse.go:24
			if d.PasswordError != "" {
//line resources/views/auth_passwords_reset.go:107
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"alert\" class=\"mt-2 text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:25
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordError)))
//line resources/views/auth_passwords_reset.go:114
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<label for=\"password-confirm\" class=\"block text-sm font-medium text-slate-700 dark:text-slate-200\">Confirm password</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<input id=\"password-confirm\" name=\"password_confirmation\" type=\"password\" required autocomplete=\"new-password\" class=\"mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 shadow-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:focus:border-slate-100\">\n")
			}
//line resources/views/auth/passwords/reset.kyse.go:31
			if d.PasswordConfirmationError != "" {
//line resources/views/auth_passwords_reset.go:134
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"alert\" class=\"mt-2 text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:32
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordConfirmationError)))
//line resources/views/auth_passwords_reset.go:141
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"pt-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<button type=\"submit\" class=\"inline-flex items-center justify-center rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-900/20 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-white\">Reset password</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
