// Code generated by `aru view:build` from verify.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

func init() { view.Register("auth.verify", renderAuthVerify) }

// renderAuthVerify renders auth.verify.
func renderAuthVerify(w io.Writer, data any) error {
	d, ok := data.(AuthPage)
	if !ok {
		return view.WrongData("auth.verify", "AuthPage", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<section class=\"overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<h1 class=\"border-b border-slate-200 px-6 py-4 text-base font-semibold tracking-tight dark:border-slate-800\">Verify your email address</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"space-y-4 px-6 py-6 text-sm text-slate-600 dark:text-slate-300\">\n")
			}
//line resources/views/auth/verify.kyse.go:12
			if d.Resent {
//line resources/views/auth_verify.go:41
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"status\" class=\"rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-200\">A fresh verification link has been sent to your email address.</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "<p>Before proceeding, please check your email for a verification link.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<form method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/verify.kyse.go:16
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.VerificationResendURL)))
//line resources/views/auth_verify.go:55
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "<p>If you did not receive the email, <button type=\"submit\" class=\"font-medium text-slate-900 underline underline-offset-4 hover:text-slate-600 dark:text-slate-100 dark:hover:text-slate-300\">click here to request another</button>.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
