// Code generated by `aru view:build` from home.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/home.kyse.go:11

// HomeData is what HomeController.Index hands this page.
type HomeData = authui.AuthPage

//line resources/views/home.go:22

func init() { view.Register("home", renderHome) }

// renderHome renders home.
func renderHome(w io.Writer, data any) error {
	d, ok := data.(HomeData)
	if !ok {
		return view.WrongData("home", "HomeData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto w-full max-w-2xl\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<section class=\"card\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<header class=\"border-b px-6 py-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<h1 class=\"text-base font-semibold tracking-tight\">Dashboard</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<div class=\"px-6 py-6 text-sm\">\n")
			}
//line resources/views/home.kyse.go:25
			if d.Status != "" {
//line resources/views/home.go:56
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<div class=\"mb-4\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t")
				}
				if err == nil {
//line resources/views/home.kyse.go:27
					_, err = io.WriteString(w, view.Text(components.Alert(components.AlertProps{Title: d.Status})))
//line resources/views/home.go:66
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t</div>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<p class=\"text-muted-foreground\">You are logged in.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
