// Code generated by `aru view:build` from home.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

func init() { view.Register("home", renderHome) }

// renderHome renders home.
func renderHome(w io.Writer, data any) error {
	d, ok := data.(AuthPage)
	if !ok {
		return view.WrongData("home", "AuthPage", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"mx-auto w-full max-w-2xl\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<section class=\"overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<h1 class=\"border-b border-slate-200 px-6 py-4 text-base font-semibold tracking-tight dark:border-slate-800\">Dashboard</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "<div class=\"px-6 py-6 text-sm text-slate-600 dark:text-slate-300\">\n")
			}
//line resources/views/home.kyse.go:12
			if d.Status != "" {
//line resources/views/home.go:41
				if err == nil {
					_, err = io.WriteString(w, "<p role=\"status\" class=\"mb-4 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-200\">")
				}
				if err == nil {
//line resources/views/home.kyse.go:13
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Status)))
//line resources/views/home.go:48
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "<p>You are logged in.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
