// Code generated by `aru view:build` from app.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/layouts/app.kyse.go:5

// Layout is what every page hands the application layout.
//
// An interface rather than a struct, and that is the whole design: a page keeps
// its own typed data -- one struct per page, so a typo in a field name is a
// compile error -- and still fits the frame, because it embeds Page and Page
// implements this. Pages carrying different data therefore share one layout,
// which is what RULE 9 asks for: one layout, not one per shape of data.
//
// This is the skeleton's declaration, repeated because make:auth replaces the
// file it lived in. It has to stay identical: views.Page asserts against it, so
// a method dropped here stops the build in resources/views/page.go, in one
// place, rather than in every page of the project at once.
type Layout interface {
	// PageTitle is what the browser tab shows.
	PageTitle() string
	// BrandName is the application name in the navigation bar.
	BrandName() string
	// CSRFToken is the token every write of this session carries.
	CSRFToken() string
	// SignedIn decides which half of the navigation bar is drawn.
	SignedIn() bool
	// SignedInName is who that half greets.
	SignedInName() string
	// HomeLink is where the brand points.
	HomeLink() string
	// LoginLink is the sign-in screen.
	LoginLink() string
	// LogoutLink is what the sign-out form posts to.
	LogoutLink() string
	// RegisterLink is the sign-up screen, or empty when registration is not
	// open -- and the link is not drawn then.
	RegisterLink() string
}

// AuthPage is what every screen of the starter kit renders from.
//
// One struct for the eight screens rather than one per page: they share a
// layout, and a page that extends a layout and declares nothing renders with
// the struct the layout declares. A field a given page does not use stays at
// its zero value and is never read -- which is cheaper than eight structs that
// repeat the same form state.
//
// The chrome is not repeated here at all: the embedded Page carries the title,
// the brand, the token and the navigation, and is what makes this struct fit
// the layout. What is left below is what a sign-in screen has and a listing
// does not.
//
// Nothing here is a helper the view reaches for on its own. There is no
// route(), no config() and no auth(): a URL, the application name and the
// signed-in user are fields the handler filled in, so a name that drifts is a
// compile error instead of a blank link.
type AuthPage struct {
	Page

	// HasPasswordReset moves the "is this route registered" question to the data: an
	// application that did not register that route hides the link rather than
	// linking to a 404.
	HasPasswordReset bool

	// The addresses these screens post to and link to, beyond the navigation
	// Page already carries. They come from the router, through the handler.
	DashboardURL          string
	PasswordRequestURL    string
	PasswordEmailURL      string
	PasswordUpdateURL     string
	PasswordConfirmURL    string
	VerificationResendURL string

	// Status is the one-shot message a redirect left behind, such as the
	// confirmation that a reset link was sent. Empty means nothing to say.
	Status string
	// Resent says a fresh verification link just went out.
	Resent bool

	// Name, Email and Remember are what the person typed on the attempt that was
	// rejected. The password is deliberately absent: it is never sent back.
	Name     string
	Email    string
	Remember bool

	// ResetToken is the one-time token carried by the link in the reset email.
	ResetToken string

	// The validation messages, one field at a time. Empty means the field was
	// accepted -- there is no @error directive to ask a bag on the side.
	NameError                 string
	EmailError                string
	PasswordError             string
	PasswordConfirmationError string
}

// Compile-time proof that these screens fit the layout above.
var _ Layout = AuthPage{}

// RememberAttribute is the checked attribute of the remember-me box, or nothing.
//
// A conditional attribute has no directive of its own, and inventing one would
// grow the DSL for a single case. What does not fit a directive is written in
// Go, which is here.
func (p AuthPage) RememberAttribute() string {
	if p.Remember {
		return "checked"
	}
	return ""
}

//line resources/views/layouts_app.go:123

func init() { view.RegisterLayout("layouts.app", renderLayoutsApp) }

// renderLayoutsApp renders the layouts.app layout.
func renderLayoutsApp(w io.Writer, data any, sections map[string]func(io.Writer) error) error {
	d, ok := data.(Layout)
	if !ok {
		return view.WrongData("layouts.app", "Layout", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<!doctype html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<html lang=\"en\" class=\"h-full\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<meta charset=\"utf-8\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<title>")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:118
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
//line resources/views/layouts_app.go:156
	}
	if err == nil {
		_, err = io.WriteString(w, "</title>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<link rel=\"icon\" href=\"/favicon.ico\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<link rel=\"stylesheet\" href=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:120
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("app.css"))))
//line resources/views/layouts_app.go:170
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:121
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("htmx.min.js"))))
//line resources/views/layouts_app.go:181
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:122
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("alpine.min.js"))))
//line resources/views/layouts_app.go:192
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<body hx-headers='{\"X-CSRF-Token\": \"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:124
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CSRFToken())))
//line resources/views/layouts_app.go:206
	}
	if err == nil {
		_, err = io.WriteString(w, "\"}' class=\"h-full bg-slate-50 text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div class=\"flex min-h-full flex-col\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<header class=\"border-b border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<nav class=\"mx-auto flex h-16 max-w-5xl items-center justify-between gap-4 px-6\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<a href=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:128
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.HomeLink())))
//line resources/views/layouts_app.go:226
	}
	if err == nil {
		_, err = io.WriteString(w, "\" class=\"text-sm font-semibold tracking-tight text-slate-900 hover:text-slate-600 dark:text-slate-100 dark:hover:text-slate-300\">")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:128
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.BrandName())))
//line resources/views/layouts_app.go:234
	}
	if err == nil {
		_, err = io.WriteString(w, "</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div class=\"flex items-center gap-1 text-sm\">\n")
	}
//line resources/views/layouts/app.kyse.go:130
	if !d.SignedIn() {
//line resources/views/layouts_app.go:244
		if err == nil {
			_, err = io.WriteString(w, "<a href=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:131
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginLink())))
//line resources/views/layouts_app.go:251
		}
		if err == nil {
			_, err = io.WriteString(w, "\" class=\"rounded-md px-3 py-2 font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-slate-100\">Login</a>\n")
		}
//line resources/views/layouts/app.kyse.go:132
		if d.RegisterLink() != "" {
//line resources/views/layouts_app.go:258
			if err == nil {
				_, err = io.WriteString(w, "<a href=\"")
			}
			if err == nil {
//line resources/views/layouts/app.kyse.go:133
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RegisterLink())))
//line resources/views/layouts_app.go:265
			}
			if err == nil {
				_, err = io.WriteString(w, "\" class=\"rounded-md px-3 py-2 font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-slate-100\">Register</a>\n")
			}
		}
	}
//line resources/views/layouts/app.kyse.go:136
	if d.SignedIn() {
//line resources/views/layouts_app.go:274
		if err == nil {
			_, err = io.WriteString(w, "<span class=\"px-3 py-2 font-medium text-slate-600 dark:text-slate-300\">")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:137
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.SignedInName())))
//line resources/views/layouts_app.go:281
		}
		if err == nil {
			_, err = io.WriteString(w, "</span>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "<form method=\"post\" action=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:138
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LogoutLink())))
//line resources/views/layouts_app.go:292
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			err = view.CSRF(w, data)
		}
		if err == nil {
			_, err = io.WriteString(w, "<button type=\"submit\" class=\"rounded-md px-3 py-2 font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-slate-100\">Logout</button>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "</form>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</nav>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</header>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<main class=\"mx-auto w-full max-w-5xl grow px-6 py-10\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "content")
	}
	if err == nil {
		_, err = io.WriteString(w, "</main>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</body>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</html>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
