// Code generated by `aru view:build` from create.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/posts/create.kyse.go:5

// PostsCreateData is what PostController.Create hands this page, and what
// Store hands it back when the submission was rejected: same view, same data,
// with the messages filled in.
type PostsCreateData struct {
	// Page is the state the layout draws. Its Token is what @csrf writes into
	// the hidden field, through Page.CSRFToken -- it comes from the page data
	// rather than from a global, because a template that reaches for request
	// state outside the data it was given is how a form ends up carrying
	// another session's token under load.
	Page
	// Form is what was typed, so a rejected submission comes back filled in.
	Form PostForm
	// Errors is the message per field, as validation produced it.
	Errors map[string][]string
}

// Compile-time proof that this page fits the layout it extends.
var _ Layout = PostsCreateData{}

// PostForm is the form as text, which is what a form carries.
//
// The value that comes back after a rejection is exactly what was typed,
// including the number that failed to parse -- retyping a whole form because one
// field was wrong is how a screen becomes unpleasant.
type PostForm struct {
	// ID is empty on creation and set on edit, where it addresses the record.
	ID string
	// Title is the Title input.
	Title string
	// Slug is the Slug input.
	Slug string
	// Body is the Body input.
	Body string
	// PublishedAt is the Published at input.
	PublishedAt string
}

// arandu:begin custom
// Anything else these forms need in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/posts_create.go:58

func init() { view.Register("posts.create", renderPostsCreate) }

// renderPostsCreate renders posts.create.
func renderPostsCreate(w io.Writer, data any) error {
	d, ok := data.(PostsCreateData)
	if !ok {
		return view.WrongData("posts.create", "PostsCreateData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<nav class=\"text-sm text-slate-500 dark:text-slate-400\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"underline underline-offset-2 hover:text-slate-900 dark:hover:text-slate-100\" href=\"/posts\">Posts</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</nav>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"mt-2 text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/posts/create.kyse.go:55
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/posts_create.go:90
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<form class=\"mt-8 space-y-6\" method=\"post\" action=\"/posts\" hx-post=\"/posts\" hx-target=\"this\" hx-swap=\"outerHTML\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"title\">Title</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"title\" name=\"title\" type=\"text\" value=\"")
			}
			if err == nil {
//line resources/views/posts/create.kyse.go:62
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.Title)))
//line resources/views/posts_create.go:119
			}
			if err == nil {
				_, err = io.WriteString(w, "\" required>\n")
			}
//line resources/views/posts/create.kyse.go:63
			if len(d.Errors["title"]) > 0 {
//line resources/views/posts_create.go:126
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/create.kyse.go:64
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["title"][0])))
//line resources/views/posts_create.go:133
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"slug\">Slug</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"slug\" name=\"slug\" type=\"text\" value=\"")
			}
			if err == nil {
//line resources/views/posts/create.kyse.go:70
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.Slug)))
//line resources/views/posts_create.go:157
			}
			if err == nil {
				_, err = io.WriteString(w, "\" required>\n")
			}
//line resources/views/posts/create.kyse.go:71
			if len(d.Errors["slug"]) > 0 {
//line resources/views/posts_create.go:164
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/create.kyse.go:72
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["slug"][0])))
//line resources/views/posts_create.go:171
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"body\">Body</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<textarea class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"body\" name=\"body\" rows=\"4\" required>")
			}
			if err == nil {
//line resources/views/posts/create.kyse.go:78
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.Body)))
//line resources/views/posts_create.go:195
			}
			if err == nil {
				_, err = io.WriteString(w, "</textarea>\n")
			}
//line resources/views/posts/create.kyse.go:79
			if len(d.Errors["body"]) > 0 {
//line resources/views/posts_create.go:202
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/create.kyse.go:80
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["body"][0])))
//line resources/views/posts_create.go:209
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"published_at\">Published at</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"published_at\" name=\"published_at\" type=\"datetime-local\" value=\"")
			}
			if err == nil {
//line resources/views/posts/create.kyse.go:86
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.PublishedAt)))
//line resources/views/posts_create.go:233
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
//line resources/views/posts/create.kyse.go:87
			if len(d.Errors["published_at"]) > 0 {
//line resources/views/posts_create.go:240
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/create.kyse.go:88
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["published_at"][0])))
//line resources/views/posts_create.go:247
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"flex items-center gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<button class=\"rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-slate-300\" type=\"submit\">Save</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<a class=\"text-sm text-slate-500 underline underline-offset-2 dark:text-slate-400\" href=\"/posts\">Cancel</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</form>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
