// Code generated by `aru view:build` from show.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/posts/show.kyse.go:5

// PostsShowData is what PostController.Show hands this page.
type PostsShowData struct {
	// Page is the state the layout draws. Its Token is also what the delete
	// button sends as a header: an hx-delete carries no form body, so the
	// hidden field a form uses would never arrive and the request would be
	// refused with 419.
	Page
	// Post is the record.
	Post PostRow
}

// Compile-time proof that this page fits the layout it extends.
var _ Layout = PostsShowData{}

// arandu:begin custom
// Anything else this page needs in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/posts_show.go:35

func init() { view.Register("posts.show", renderPostsShow) }

// renderPostsShow renders posts.show.
func renderPostsShow(w io.Writer, data any) error {
	d, ok := data.(PostsShowData)
	if !ok {
		return view.WrongData("posts.show", "PostsShowData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<nav class=\"text-sm text-slate-500 dark:text-slate-400\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"underline underline-offset-2 hover:text-slate-900 dark:hover:text-slate-100\" href=\"/posts\">Posts</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</nav>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mt-2 flex items-center justify-between gap-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h1 class=\"text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:33
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/posts_show.go:70
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"flex items-center gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<a class=\"rounded-md border border-slate-300 px-3 py-2 text-sm font-medium hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-900\" href=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:35
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.ID)))
//line resources/views/posts_show.go:84
			}
			if err == nil {
				_, err = io.WriteString(w, "/edit\">Edit</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<button class=\"rounded-md border border-red-300 px-3 py-2 text-sm font-medium text-red-700 hover:bg-red-50 dark:border-red-900 dark:text-red-400 dark:hover:bg-red-950\" type=\"button\" hx-delete=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:36
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.ID)))
//line resources/views/posts_show.go:95
			}
			if err == nil {
				_, err = io.WriteString(w, "\" hx-headers='{\"X-CSRF-Token\": \"")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:36
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Token)))
//line resources/views/posts_show.go:103
			}
			if err == nil {
				_, err = io.WriteString(w, "\"}' hx-confirm=\"Delete this post?\">Delete</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<dl class=\"mt-8 divide-y divide-slate-100 border-t border-slate-200 text-sm dark:divide-slate-900 dark:border-slate-800\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"grid grid-cols-3 gap-4 py-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-slate-500 dark:text-slate-400\">Title</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"col-span-2\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:43
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Title)))
//line resources/views/posts_show.go:132
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"grid grid-cols-3 gap-4 py-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-slate-500 dark:text-slate-400\">Slug</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"col-span-2\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:47
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Slug)))
//line resources/views/posts_show.go:152
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"grid grid-cols-3 gap-4 py-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-slate-500 dark:text-slate-400\">Body</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"col-span-2\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:51
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Body)))
//line resources/views/posts_show.go:172
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"grid grid-cols-3 gap-4 py-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-slate-500 dark:text-slate-400\">Published at</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"col-span-2\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:55
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.PublishedAt)))
//line resources/views/posts_show.go:192
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"grid grid-cols-3 gap-4 py-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-slate-500 dark:text-slate-400\">Created</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"col-span-2\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:59
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Created)))
//line resources/views/posts_show.go:212
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</dl>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
