// Code generated by `aru view:build` from edit.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/posts/edit.kyse.go:5

// PostsEditData is what PostController.Edit hands this page: the form
// filled in with a stored record, or with what was typed when Update rejected it.
type PostsEditData struct {
	// Page is the state the layout draws. Its Token is what @csrf writes into
	// the hidden field.
	Page
	// Form is the record as text.
	Form PostForm
	// Errors is the message per field, as validation produced it.
	Errors map[string][]string
}

// Compile-time proof that this page fits the layout it extends.
var _ Layout = PostsEditData{}

// arandu:begin custom
// Anything else this page needs in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/posts_edit.go:36

func init() { view.Register("posts.edit", renderPostsEdit) }

// renderPostsEdit renders posts.edit.
func renderPostsEdit(w io.Writer, data any) error {
	d, ok := data.(PostsEditData)
	if !ok {
		return view.WrongData("posts.edit", "PostsEditData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<nav class=\"text-sm text-slate-500 dark:text-slate-400\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"underline underline-offset-2 hover:text-slate-900 dark:hover:text-slate-100\" href=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:30
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ID)))
//line resources/views/posts_edit.go:59
			}
			if err == nil {
				_, err = io.WriteString(w, "\">Back</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</nav>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"mt-2 text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:33
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/posts_edit.go:76
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<!-- hx-put, and no action: a browser form can only send GET and POST, and\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t     the update route is PUT. HTMX sends the real method, which is why this\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t     stack does not need a hidden _method field. -->\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<form class=\"mt-8 space-y-6\" hx-put=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:38
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ID)))
//line resources/views/posts_edit.go:99
			}
			if err == nil {
				_, err = io.WriteString(w, "\" hx-target=\"this\" hx-swap=\"outerHTML\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"title\">Title</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"title\" name=\"title\" type=\"text\" value=\"")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:43
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.Title)))
//line resources/views/posts_edit.go:122
			}
			if err == nil {
				_, err = io.WriteString(w, "\" required>\n")
			}
//line resources/views/posts/edit.kyse.go:44
			if len(d.Errors["title"]) > 0 {
//line resources/views/posts_edit.go:129
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/edit.kyse.go:45
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["title"][0])))
//line resources/views/posts_edit.go:136
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"slug\">Slug</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"slug\" name=\"slug\" type=\"text\" value=\"")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:51
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.Slug)))
//line resources/views/posts_edit.go:160
			}
			if err == nil {
				_, err = io.WriteString(w, "\" required>\n")
			}
//line resources/views/posts/edit.kyse.go:52
			if len(d.Errors["slug"]) > 0 {
//line resources/views/posts_edit.go:167
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/edit.kyse.go:53
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["slug"][0])))
//line resources/views/posts_edit.go:174
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"body\">Body</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<textarea class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"body\" name=\"body\" rows=\"4\" required>")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:59
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.Body)))
//line resources/views/posts_edit.go:198
			}
			if err == nil {
				_, err = io.WriteString(w, "</textarea>\n")
			}
//line resources/views/posts/edit.kyse.go:60
			if len(d.Errors["body"]) > 0 {
//line resources/views/posts_edit.go:205
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/edit.kyse.go:61
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["body"][0])))
//line resources/views/posts_edit.go:212
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"space-y-1\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<label class=\"block text-sm font-medium\" for=\"published_at\">Published at</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"block w-full rounded-md border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900\" id=\"published_at\" name=\"published_at\" type=\"datetime-local\" value=\"")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:67
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.PublishedAt)))
//line resources/views/posts_edit.go:236
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
//line resources/views/posts/edit.kyse.go:68
			if len(d.Errors["published_at"]) > 0 {
//line resources/views/posts_edit.go:243
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-sm text-red-600 dark:text-red-400\">")
				}
				if err == nil {
//line resources/views/posts/edit.kyse.go:69
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Errors["published_at"][0])))
//line resources/views/posts_edit.go:250
				}
				if err == nil {
					_, err = io.WriteString(w, "</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"flex items-center gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<button class=\"rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-slate-300\" type=\"submit\">Save</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<a class=\"text-sm text-slate-500 underline underline-offset-2 dark:text-slate-400\" href=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:75
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ID)))
//line resources/views/posts_edit.go:274
			}
			if err == nil {
				_, err = io.WriteString(w, "\">Cancel</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</form>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
