// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/posts/index.kyse.go:5

// PostsIndexData is what PostController.Index hands this page.
type PostsIndexData struct {
	// Page is the state the layout draws: the title, the brand, the CSRF token
	// and the navigation. Embedded rather than repeated, and what makes this
	// struct fit the layout.
	Page
	// Posts is the page of records.
	Posts []PostRow
	// NextCursor is the keyset cursor of the following page. It is empty on the
	// last page, and the link is not rendered then.
	NextCursor string
}

// Compile-time proof that this page fits the layout it extends.
var _ Layout = PostsIndexData{}

// PostRow is one record, formatted for display by the controller.
type PostRow struct {
	// ID is what the row links to.
	ID string
	// Title is the Title column.
	Title string
	// Slug is the Slug column.
	Slug string
	// Body is the Body column.
	Body string
	// PublishedAt is the Published at column.
	PublishedAt string
	// Created is the creation timestamp, already formatted.
	Created string
}

// arandu:begin custom
// Anything else these pages need in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/posts_index.go:53

func init() { view.Register("posts.index", renderPostsIndex) }

// renderPostsIndex renders posts.index.
func renderPostsIndex(w io.Writer, data any) error {
	d, ok := data.(PostsIndexData)
	if !ok {
		return view.WrongData("posts.index", "PostsIndexData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"flex items-center justify-between gap-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h1 class=\"text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/posts/index.kyse.go:47
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/posts_index.go:76
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"rounded-md border border-slate-300 px-3 py-2 text-sm font-medium hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-900\" href=\"/posts/create\">New post</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/index.kyse.go:51
			if len(d.Posts) == 0 {
//line resources/views/posts_index.go:92
				if err == nil {
					_, err = io.WriteString(w, "\t<p class=\"mt-8 text-sm text-slate-500 dark:text-slate-400\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\tNo post yet. <a class=\"underline underline-offset-2\" href=\"/posts/create\">Add the first one</a>.\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/index.kyse.go:57
			if len(d.Posts) > 0 {
//line resources/views/posts_index.go:108
				if err == nil {
					_, err = io.WriteString(w, "\t<div class=\"mt-8 overflow-x-auto\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t<table class=\"w-full border-collapse text-left text-sm\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<thead class=\"border-b border-slate-200 text-slate-500 dark:border-slate-800 dark:text-slate-400\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<tr>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Title</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Slug</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Body</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Published at</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<th class=\"py-2 font-medium\">Created</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t</tr>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</thead>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<tbody>\n")
				}
//line resources/views/posts/index.kyse.go:70
				for _, post := range d.Posts {
					_ = post
//line resources/views/posts_index.go:148
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t<tr class=\"border-b border-slate-100 dark:border-slate-900\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 pr-4\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t<a class=\"font-medium underline underline-offset-2\" href=\"/posts/")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:73
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(post.ID)))
//line resources/views/posts_index.go:161
					}
					if err == nil {
						_, err = io.WriteString(w, "\">")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:73
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(post.Title)))
//line resources/views/posts_index.go:169
					}
					if err == nil {
						_, err = io.WriteString(w, "</a>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 pr-4\">")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:75
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(post.Slug)))
//line resources/views/posts_index.go:183
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 pr-4\">")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:76
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(post.Body)))
//line resources/views/posts_index.go:194
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 pr-4\">")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:77
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(post.PublishedAt)))
//line resources/views/posts_index.go:205
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 text-slate-500 dark:text-slate-400\">")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:78
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(post.Created)))
//line resources/views/posts_index.go:216
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t</tr>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</tbody>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</table>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t</div>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/index.kyse.go:86
			if d.NextCursor != "" {
//line resources/views/posts_index.go:240
				if err == nil {
					_, err = io.WriteString(w, "\t<a class=\"mt-6 inline-block text-sm underline underline-offset-2\" href=\"/posts?cursor=")
				}
				if err == nil {
//line resources/views/posts/index.kyse.go:87
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.NextCursor)))
//line resources/views/posts_index.go:247
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Next page</a>\n")
				}
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
