// Code generated by `aru view:build` from welcome.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
)

//line resources/views/welcome.kyse.go:7

// WelcomeData is what the landing page draws.
type WelcomeData = authui.AuthPage

//line resources/views/welcome.go:21

func init() { view.Register("welcome", renderWelcome) }

// renderWelcome renders welcome.
func renderWelcome(w io.Writer, data any) error {
	d, ok := data.(WelcomeData)
	if !ok {
		return view.WrongData("welcome", "WelcomeData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto flex w-full max-w-2xl flex-col items-start gap-6 py-12\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h1 class=\"text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/welcome.kyse.go:16
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.AppName)))
//line resources/views/welcome.go:44
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<p class=\"text-muted-foreground text-base\">The routing, the controllers and the markup are on the server. There is no API layer in between and no router in the browser, and what travels on an interaction is a fragment of HTML.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"flex flex-wrap items-center gap-3\">\n")
			}
//line resources/views/welcome.kyse.go:19
			if d.Authenticated {
//line resources/views/welcome.go:57
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<a href=\"")
				}
				if err == nil {
//line resources/views/welcome.kyse.go:20
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.DashboardURL)))
//line resources/views/welcome.go:64
				}
				if err == nil {
					_, err = io.WriteString(w, "\" class=\"btn\">Dashboard</a>\n")
				}
			}
//line resources/views/welcome.kyse.go:22
			if !d.Authenticated {
//line resources/views/welcome.go:72
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<a href=\"")
				}
				if err == nil {
//line resources/views/welcome.kyse.go:23
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginURL)))
//line resources/views/welcome.go:79
				}
				if err == nil {
					_, err = io.WriteString(w, "\" class=\"btn\">Login</a>\n")
				}
//line resources/views/welcome.kyse.go:24
				if d.RegisterURL != "" {
//line resources/views/welcome.go:86
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<a href=\"")
					}
					if err == nil {
//line resources/views/welcome.kyse.go:25
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RegisterURL)))
//line resources/views/welcome.go:93
					}
					if err == nil {
						_, err = io.WriteString(w, "\" class=\"btn\" data-variant=\"outline\">Register</a>\n")
					}
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
