// Code generated by `aru view:build` from confirm.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package passwords

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/auth/passwords/confirm.kyse.go:11

// ConfirmData is what the password-confirmation screen draws.
type ConfirmData = authui.AuthPage

//line resources/views/auth/passwords/confirm.go:22

func init() { view.Register("auth.passwords.confirm", renderAuthPasswordsConfirm) }

// renderAuthPasswordsConfirm renders auth.passwords.confirm.
func renderAuthPasswordsConfirm(w io.Writer, data any) error {
	d, ok := data.(ConfirmData)
	if !ok {
		return view.WrongData("auth.passwords.confirm", "ConfirmData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<section class=\"card\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<header class=\"border-b px-6 py-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<h1 class=\"text-base font-semibold tracking-tight\">Confirm your password</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<form class=\"flex flex-col gap-4 px-6 py-6\" method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/passwords/confirm.kyse.go:25
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordConfirmURL)))
//line resources/views/auth/passwords/confirm.go:60
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<p class=\"text-muted-foreground text-sm\">This is a protected area. Confirm your password before going on.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/passwords/confirm.kyse.go:30
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "password", Label: "Password", Type: "password", Error: d.PasswordError, Autocomplete: "current-password", Required: true, Autofocus: true})))
//line resources/views/auth/passwords/confirm.go:83
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<button type=\"submit\" class=\"btn\">Confirm</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
