// Code generated by `aru view:build` from reset.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package passwords

import (
	"html/template"
	"io"

	authui "github.com/arandu-io/examples/app/Http/Controllers/Auth"
	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/auth/passwords/reset.kyse.go:11

// ResetData is what the new-password screen draws.
type ResetData = authui.AuthPage

//line resources/views/auth/passwords/reset.go:22

func init() { view.Register("auth.passwords.reset", renderAuthPasswordsReset) }

// renderAuthPasswordsReset renders auth.passwords.reset.
func renderAuthPasswordsReset(w io.Writer, data any) error {
	d, ok := data.(ResetData)
	if !ok {
		return view.WrongData("auth.passwords.reset", "ResetData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"mx-auto w-full max-w-md\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<section class=\"card\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<header class=\"border-b px-6 py-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<h1 class=\"text-base font-semibold tracking-tight\">Choose a new password</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<form class=\"flex flex-col gap-4 px-6 py-6\" method=\"post\" action=\"")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:25
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PasswordUpdateURL)))
//line resources/views/auth/passwords/reset.go:60
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<input type=\"hidden\" name=\"token\" value=\"")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:30
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.ResetToken)))
//line resources/views/auth/passwords/reset.go:74
			}
			if err == nil {
				_, err = io.WriteString(w, "\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:32
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "email", Label: "Email", Type: "email", Value: d.Email, Error: d.EmailError, Autocomplete: "email", Required: true})))
//line resources/views/auth/passwords/reset.go:88
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:38
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "password", Label: "New password", Type: "password", Error: d.PasswordError, Hint: "At least twelve characters.", Autocomplete: "new-password", Required: true, Autofocus: true})))
//line resources/views/auth/passwords/reset.go:102
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t")
			}
			if err == nil {
//line resources/views/auth/passwords/reset.kyse.go:45
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "password_confirmation", Label: "Confirm the new password", Type: "password", Error: d.PasswordConfirmationError, Autocomplete: "new-password", Required: true})))
//line resources/views/auth/passwords/reset.go:116
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<button type=\"submit\" class=\"btn\">Change it</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t</form>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</section>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
