// Code generated by `aru view:build` from edit.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package posts

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/posts/edit.kyse.go:11

// PostsEditData is what PostController.Edit hands this page: the form
// filled in with a stored record, or with what was typed when Update rejected it.
type PostsEditData struct {
	// Page is the state the layout draws. Its Token is what @csrf writes into
	// the hidden field.
	view.Page
	// Form is the record as text.
	Form PostForm
	// Errors is the message per field, as validation produced it.
	Errors map[string][]string
}

// FieldError is the first message for a field, or empty.
//
// A method rather than a lookup in the markup: a view that indexes a map has to
// check the length first, and d.Errors["title"][0] without that check panics
// on the happy path -- which is the request where nothing was wrong.
func (d PostsEditData) FieldError(field string) string {
	if msgs := d.Errors[field]; len(msgs) > 0 {
		return msgs[0]
	}
	return ""
}

// Compile-time proof that this page fits the layout it extends.
var _ view.Layout = PostsEditData{}

// arandu:begin custom
// Anything else this page needs in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/posts/edit.go:49

func init() { view.Register("posts.edit", renderPostsEdit) }

// renderPostsEdit renders posts.edit.
func renderPostsEdit(w io.Writer, data any) error {
	d, ok := data.(PostsEditData)
	if !ok {
		return view.WrongData("posts.edit", "PostsEditData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<nav class=\"text-sm text-slate-500 dark:text-slate-400\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"underline underline-offset-2 hover:text-slate-900 dark:hover:text-slate-100\" href=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:48
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ID)))
//line resources/views/posts/edit.go:72
			}
			if err == nil {
				_, err = io.WriteString(w, "\">Back</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</nav>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"mt-2 text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:51
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/posts/edit.go:89
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<!-- hx-put, and no action: a browser form can only send GET and POST, and\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\tthe update route is PUT. HTMX sends the real method, which is why this\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\tstack does not need a hidden _method field. -->\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<form class=\"mt-8 space-y-6\" hx-put=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:56
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ID)))
//line resources/views/posts/edit.go:112
			}
			if err == nil {
				_, err = io.WriteString(w, "\" hx-target=\"this\" hx-swap=\"outerHTML\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:59
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "title", Label: "Title", Type: "text", Value: d.Form.Title, Error: d.FieldError("title"), Required: true})))
//line resources/views/posts/edit.go:129
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:68
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "slug", Label: "Slug", Type: "text", Value: d.Form.Slug, Error: d.FieldError("slug"), Required: true})))
//line resources/views/posts/edit.go:143
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:77
				_, err = io.WriteString(w, view.Text(components.Textarea(components.TextareaProps{Name: "body", Label: "Body", Value: d.Form.Body, Error: d.FieldError("body"), Rows: 6, Required: true})))
//line resources/views/posts/edit.go:157
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:86
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "published_at", Label: "Published at", Type: "datetime-local", Value: d.Form.PublishedAt, Error: d.FieldError("published_at")})))
//line resources/views/posts/edit.go:171
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"flex items-center gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<button class=\"rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-slate-300\" type=\"submit\">Save</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<a class=\"text-sm text-slate-500 underline underline-offset-2 dark:text-slate-400\" href=\"/posts/")
			}
			if err == nil {
//line resources/views/posts/edit.kyse.go:96
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ID)))
//line resources/views/posts/edit.go:191
			}
			if err == nil {
				_, err = io.WriteString(w, "\">Cancel</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</form>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
