// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package posts

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/posts/index.kyse.go:11

// PostsIndexData is what PostController.Index hands this page.
type PostsIndexData struct {
	// view.Page is the chrome the layout draws: the title, the description, the
	// CSRF token and the navigation. Embedded rather than repeated, and what
	// makes this struct fit the layout.
	view.Page

	// Posts is the page of records.
	Posts []PostRow
	// NextCursor is the keyset cursor of the following page. It is empty on the
	// last page, and the link is not rendered then.
	NextCursor string
	// NewURL is where the "write one" button goes, and it is empty for a reader
	// who cannot write. An empty URL draws no button, which is how the policy
	// reaches the markup without the markup asking it anything.
	NewURL string
}

// Compile-time proof that this page fits the layout it extends.
var _ view.Layout = PostsIndexData{}

// PostRow is one record, formatted for display by the controller.
//
// Formatted there rather than here: a date is a decision about presentation,
// and a view that formats one is a view with a locale in it.
type PostRow struct {
	// ID is what the row links to.
	ID string
	// Title is the Title column.
	Title string
	// Slug is the Slug column, and what the public URL is built from.
	Slug string
	// Body is the Body column.
	Body string
	// Excerpt is the opening of the body, cut to a line.
	Excerpt string
	// PublishedAt is the publication date, already formatted. It is empty on a
	// draft, and that is what the badge below reads.
	PublishedAt string
	// Created is the creation timestamp, already formatted.
	Created string
	// URL is where this post is read.
	URL string
	// Comments is how many comments it has.
	Comments string
}

// Status is the word on the badge: what state this post is in.
func (r PostRow) Status() string {
	if r.PublishedAt == "" {
		return "draft"
	}
	return "published"
}

// StatusVariant styles that badge. A draft is not an error, so it is the quiet
// variant rather than the loud one.
func (r PostRow) StatusVariant() string {
	if r.PublishedAt == "" {
		return "outline"
	}
	return "secondary"
}

// Meta is the grey line under the title: when it went out, and how many people
// answered.
func (r PostRow) Meta() string {
	when := r.PublishedAt
	if when == "" {
		when = "not published"
	}
	return when + " · " + r.Comments + " comments"
}

//line resources/views/posts/index.go:92

func init() { view.Register("posts.index", renderPostsIndex) }

// renderPostsIndex renders posts.index.
func renderPostsIndex(w io.Writer, data any) error {
	d, ok := data.(PostsIndexData)
	if !ok {
		return view.WrongData("posts.index", "PostsIndexData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<header class=\"flex items-end justify-between gap-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<h1 class=\"text-2xl font-semibold tracking-tight\">Posts</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<p class=\"text-muted-foreground mt-1 text-sm\">Everything written here, newest first.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
//line resources/views/posts/index.kyse.go:95
			if d.NewURL != "" {
//line resources/views/posts/index.go:123
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<a class=\"btn\" href=\"")
				}
				if err == nil {
//line resources/views/posts/index.kyse.go:96
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.NewURL)))
//line resources/views/posts/index.go:130
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Write one</a>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/index.kyse.go:100
			if len(d.Posts) > 0 {
//line resources/views/posts/index.go:144
				if err == nil {
					_, err = io.WriteString(w, "\t\t<ul class=\"mt-8 flex flex-col gap-4\">\n")
				}
//line resources/views/posts/index.kyse.go:102
				for _, post := range d.Posts {
					_ = post
//line resources/views/posts/index.go:151
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t<li>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t")
					}
					if err == nil {
//line resources/views/posts/index.kyse.go:104
						_, err = io.WriteString(w, view.Text(components.Card(components.CardProps{Title: post.Title, Description: post.Excerpt, Href: post.URL, Meta: post.Meta(), Badge: post.Status(), BadgeVariant: post.StatusVariant()})))
//line resources/views/posts/index.go:161
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t</li>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</ul>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/index.kyse.go:119
			if len(d.Posts) == 0 {
//line resources/views/posts/index.go:179
				if err == nil {
					_, err = io.WriteString(w, "\t\t<div class=\"mt-8\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t")
				}
				if err == nil {
//line resources/views/posts/index.kyse.go:121
					_, err = io.WriteString(w, view.Text(components.Empty(components.EmptyProps{Title: "Nothing here yet", Message: "The first post is the hardest.", ActionLabel: "Write one", ActionURL: d.NewURL})))
//line resources/views/posts/index.go:189
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</div>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/index.kyse.go:130
			if d.NextCursor != "" {
//line resources/views/posts/index.go:203
				if err == nil {
					_, err = io.WriteString(w, "\t\t<nav class=\"mt-8 flex justify-center\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<a class=\"btn\" data-variant=\"outline\" href=\"?cursor=")
				}
				if err == nil {
//line resources/views/posts/index.kyse.go:132
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.NextCursor)))
//line resources/views/posts/index.go:213
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Older posts</a>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</nav>\n")
				}
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
