// Code generated by `aru view:build` from show.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package posts

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/posts/show.kyse.go:11

// PostsShowData is what PostController.Show hands this page.
type PostsShowData struct {
	// view.Page carries the title, the description and the canonical URL, which
	// is what makes a post indexable on its own terms rather than under the
	// application's name.
	view.Page

	// Post is what is being read.
	Post PostRow

	// Comments is what people answered, oldest first, because a conversation
	// reads forwards.
	Comments []CommentRow
	// CommentURL is where a new comment is posted. It is empty for somebody the
	// policy will not accept, and an empty URL draws no form -- so the rule
	// reaches the markup as data rather than as a question the view asks.
	CommentURL string

	// EditURL and DeleteURL are empty for a reader. Same reason.
	EditURL   string
	DeleteURL string
}

// Compile-time proof that this page fits the layout it extends.
var _ view.Layout = PostsShowData{}

// CommentRow is one comment, formatted for display by the controller.
type CommentRow struct {
	// ID is what a moderation action addresses.
	ID string
	// Author is the display name of whoever wrote it.
	Author string
	// Body is what they said.
	Body string
	// Created is when, already formatted.
	Created string
	// Approved says whether it is visible to everybody. A comment awaiting
	// moderation is shown to its author and to an administrator, marked.
	Approved bool
}

// Badge is the word beside a comment that is not public yet, or nothing.
func (c CommentRow) Badge() string {
	if c.Approved {
		return ""
	}
	return "awaiting review"
}

//line resources/views/posts/show.go:67

func init() { view.Register("posts.show", renderPostsShow) }

// renderPostsShow renders posts.show.
func renderPostsShow(w io.Writer, data any) error {
	d, ok := data.(PostsShowData)
	if !ok {
		return view.WrongData("posts.show", "PostsShowData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<article class=\"mx-auto w-full max-w-2xl\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<h1 class=\"text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:67
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Title)))
//line resources/views/posts/show.go:93
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<p class=\"text-muted-foreground mt-2 text-sm\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:68
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Meta())))
//line resources/views/posts/show.go:104
			}
			if err == nil {
				_, err = io.WriteString(w, "</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"mt-8 text-base leading-7 whitespace-pre-line\">")
			}
			if err == nil {
//line resources/views/posts/show.kyse.go:74
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Post.Body)))
//line resources/views/posts/show.go:121
			}
			if err == nil {
				_, err = io.WriteString(w, "</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/show.kyse.go:76
			if d.EditURL != "" {
//line resources/views/posts/show.go:131
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<footer class=\"mt-10 flex items-center gap-3 border-t pt-6\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<a class=\"btn\" data-variant=\"outline\" data-size=\"sm\" href=\"")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:78
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.EditURL)))
//line resources/views/posts/show.go:141
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Edit</a>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<button type=\"button\" class=\"btn\" data-variant=\"destructive\" data-size=\"sm\"\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\tonclick=\"deletePost.showModal()\">Delete</button>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</footer>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:83
					_, err = io.WriteString(w, view.Text(components.Dialog(components.DialogProps{ID: "deletePost", Title: "Delete this post?", Message: "The post and every comment on it go with it. This cannot be undone.", ConfirmLabel: "Delete it", ConfirmVariant: "destructive", Action: d.DeleteURL, Token: d.CSRFToken()})))
//line resources/views/posts/show.go:164
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</article>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<section class=\"mx-auto mt-16 w-full max-w-2xl border-t pt-10\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h2 class=\"text-lg font-semibold tracking-tight\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\tComments\n")
			}
//line resources/views/posts/show.kyse.go:98
			if len(d.Comments) > 0 {
//line resources/views/posts/show.go:187
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:99
					_, err = io.WriteString(w, view.Text(components.Badge(components.BadgeProps{Label: d.Post.Comments, Variant: "secondary"})))
//line resources/views/posts/show.go:194
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</h2>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/show.kyse.go:103
			if len(d.Comments) > 0 {
//line resources/views/posts/show.go:208
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<ul class=\"mt-6 flex flex-col gap-6\">\n")
				}
//line resources/views/posts/show.kyse.go:105
				for _, comment := range d.Comments {
					_ = comment
//line resources/views/posts/show.go:215
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<li class=\"flex gap-3\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t")
					}
					if err == nil {
//line resources/views/posts/show.kyse.go:107
						_, err = io.WriteString(w, view.Text(components.Avatar(components.AvatarProps{Name: comment.Author, Size: "sm"})))
//line resources/views/posts/show.go:225
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t<div class=\"min-w-0 flex-1\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t<div class=\"flex items-center gap-2\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t<span class=\"text-sm font-medium\">")
					}
					if err == nil {
//line resources/views/posts/show.kyse.go:110
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Author)))
//line resources/views/posts/show.go:242
					}
					if err == nil {
						_, err = io.WriteString(w, "</span>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t<span class=\"text-muted-foreground text-xs\">")
					}
					if err == nil {
//line resources/views/posts/show.kyse.go:111
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Created)))
//line resources/views/posts/show.go:253
					}
					if err == nil {
						_, err = io.WriteString(w, "</span>\n")
					}
//line resources/views/posts/show.kyse.go:112
					if comment.Badge() != "" {
//line resources/views/posts/show.go:260
						if err == nil {
							_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t\t")
						}
						if err == nil {
//line resources/views/posts/show.kyse.go:113
							_, err = io.WriteString(w, view.Text(components.Badge(components.BadgeProps{Label: comment.Badge(), Variant: "outline"})))
//line resources/views/posts/show.go:267
						}
						if err == nil {
							_, err = io.WriteString(w, "\n")
						}
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t<p class=\"mt-1 text-sm whitespace-pre-line\">")
					}
					if err == nil {
//line resources/views/posts/show.kyse.go:116
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Body)))
//line resources/views/posts/show.go:282
					}
					if err == nil {
						_, err = io.WriteString(w, "</p>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t</li>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</ul>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/show.kyse.go:123
			if len(d.Comments) == 0 {
//line resources/views/posts/show.go:303
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-muted-foreground mt-6 text-sm\">Nobody has said anything yet.</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/show.kyse.go:127
			if d.CommentURL != "" {
//line resources/views/posts/show.go:313
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<form class=\"mt-10 flex flex-col gap-4\" method=\"post\" action=\"")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:131
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CommentURL)))
//line resources/views/posts/show.go:320
				}
				if err == nil {
					_, err = io.WriteString(w, "\"\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\thx-post=\"")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:132
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CommentURL)))
//line resources/views/posts/show.go:331
				}
				if err == nil {
					_, err = io.WriteString(w, "\" hx-target=\"this\" hx-swap=\"outerHTML\">\n")
				}
				if err == nil {
					err = view.CSRF(w, data)
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:135
					_, err = io.WriteString(w, view.Text(components.Textarea(components.TextareaProps{Name: "body", Label: "Say something", Rows: 4, Placeholder: "Be kind.", Hint: "Comments are reviewed before they appear.", Required: true})))
//line resources/views/posts/show.go:348
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<div>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<button type=\"submit\" class=\"btn\">Post the comment</button>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t</div>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</form>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/posts/show.kyse.go:150
			if d.CommentURL == "" {
//line resources/views/posts/show.go:374
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<p class=\"text-muted-foreground mt-10 text-sm\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<a class=\"hover:underline\" href=\"")
				}
				if err == nil {
//line resources/views/posts/show.kyse.go:152
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginLink())))
//line resources/views/posts/show.go:384
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Sign in</a> to leave a comment.\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</section>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
