// Code generated by `aru view:build` from comments.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package admin

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/admin/comments.kyse.go:7

// CommentsData is the moderation queue.
type CommentsData struct {
	Chrome

	// Comments is everything written, newest state first: what is waiting is
	// what somebody came here to do.
	Comments []CommentRow
}

// CommentRow is one comment, with the two addresses that act on it.
//
// The URLs come from the controller, built from route names. A view that wrote
// "/admin/comments/"+id would keep compiling after the route moved, and the
// button would 404 in silence.
type CommentRow struct {
	ID      string
	Author  string
	Body    string
	Created string
	// Approved says whether it is public. It decides which button is drawn.
	Approved bool

	ApproveURL string
	DeleteURL  string
}

// Status is the word on the badge.
func (r CommentRow) Status() string {
	if r.Approved {
		return "public"
	}
	return "awaiting review"
}

// StatusVariant styles it. Waiting is not an error, so it is the quiet variant.
func (r CommentRow) StatusVariant() string {
	if r.Approved {
		return "secondary"
	}
	return "outline"
}

//line resources/views/admin/comments.go:60

func init() { view.Register("admin.comments", renderAdminComments) }

// renderAdminComments renders admin.comments.
func renderAdminComments(w io.Writer, data any) error {
	d, ok := data.(CommentsData)
	if !ok {
		return view.WrongData("admin.comments", "CommentsData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h1 class=\"text-2xl font-semibold tracking-tight\">Comments</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<p class=\"text-muted-foreground mt-1 text-sm\">Nothing appears on a post until it is approved here.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/admin/comments.kyse.go:59
			if len(d.Comments) > 0 {
//line resources/views/admin/comments.go:91
				if err == nil {
					_, err = io.WriteString(w, "\t\t<ul class=\"mt-8 flex flex-col gap-4\">\n")
				}
//line resources/views/admin/comments.kyse.go:61
				for _, comment := range d.Comments {
					_ = comment
//line resources/views/admin/comments.go:98
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t<li class=\"card p-5\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<div class=\"flex items-start justify-between gap-4\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t<div class=\"flex min-w-0 gap-3\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t")
					}
					if err == nil {
//line resources/views/admin/comments.kyse.go:65
						_, err = io.WriteString(w, view.Text(components.Avatar(components.AvatarProps{Name: comment.Author, Size: "sm"})))
//line resources/views/admin/comments.go:114
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t<div class=\"min-w-0\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t<div class=\"flex items-center gap-2\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t\t<span class=\"text-sm font-medium\">")
					}
					if err == nil {
//line resources/views/admin/comments.kyse.go:68
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Author)))
//line resources/views/admin/comments.go:131
					}
					if err == nil {
						_, err = io.WriteString(w, "</span>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t\t<span class=\"text-muted-foreground text-xs\">")
					}
					if err == nil {
//line resources/views/admin/comments.kyse.go:69
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Created)))
//line resources/views/admin/comments.go:142
					}
					if err == nil {
						_, err = io.WriteString(w, "</span>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t<p class=\"mt-1 text-sm whitespace-pre-line\">")
					}
					if err == nil {
//line resources/views/admin/comments.kyse.go:71
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Body)))
//line resources/views/admin/comments.go:156
					}
					if err == nil {
						_, err = io.WriteString(w, "</p>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t")
					}
					if err == nil {
//line resources/views/admin/comments.kyse.go:74
						_, err = io.WriteString(w, view.Text(components.Badge(components.BadgeProps{Label: comment.Status(), Variant: comment.StatusVariant()})))
//line resources/views/admin/comments.go:173
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<div class=\"mt-4 flex items-center gap-2 border-t pt-4\">\n")
					}
//line resources/views/admin/comments.kyse.go:78
					if !comment.Approved {
//line resources/views/admin/comments.go:189
						if err == nil {
							_, err = io.WriteString(w, "\t\t\t\t\t\t\t<form method=\"post\" action=\"")
						}
						if err == nil {
//line resources/views/admin/comments.kyse.go:79
							_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.ApproveURL)))
//line resources/views/admin/comments.go:196
						}
						if err == nil {
							_, err = io.WriteString(w, "\">\n")
						}
						if err == nil {
							err = view.CSRF(w, data)
						}
						if err == nil {
							_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\" data-size=\"sm\">Approve</button>\n")
						}
						if err == nil {
							_, err = io.WriteString(w, "\t\t\t\t\t\t\t</form>\n")
						}
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t<form method=\"post\" action=\"")
					}
					if err == nil {
//line resources/views/admin/comments.kyse.go:84
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.DeleteURL)))
//line resources/views/admin/comments.go:217
					}
					if err == nil {
						_, err = io.WriteString(w, "\">\n")
					}
					if err == nil {
						err = view.CSRF(w, data)
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\" data-variant=\"ghost\" data-size=\"sm\">Delete</button>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t</form>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t</div>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t</li>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</ul>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/admin/comments.kyse.go:94
			if len(d.Comments) == 0 {
//line resources/views/admin/comments.go:247
				if err == nil {
					_, err = io.WriteString(w, "\t\t<div class=\"mt-8\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t")
				}
				if err == nil {
//line resources/views/admin/comments.kyse.go:96
					_, err = io.WriteString(w, view.Text(components.Empty(components.EmptyProps{Title: "Nothing to review", Message: "Every comment written so far has been dealt with."})))
//line resources/views/admin/comments.go:257
				}
				if err == nil {
					_, err = io.WriteString(w, "\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</div>\n")
				}
			}
			return err
		},
	}
	return view.RenderInto(w, "admin.layout", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
