// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package admin

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/admin/index.kyse.go:5

// IndexData is the moderation dashboard: what is waiting, and what there is.
//
// The counts arrive as numbers rather than as the records they were counted
// from. A screen that receives two hundred rows to print the number 200 is a
// screen that gets slower every week.
type IndexData struct {
	Chrome

	// Published and Drafts are how many posts are in each state.
	Published int
	Drafts    int
	// Comments is the total, and Waiting is how many of them are not public
	// yet. Waiting is the only one that is a job to do.
	Comments int
	Waiting  int
}

//line resources/views/admin/index.go:34

func init() { view.Register("admin.index", renderAdminIndex) }

// renderAdminIndex renders admin.index.
func renderAdminIndex(w io.Writer, data any) error {
	d, ok := data.(IndexData)
	if !ok {
		return view.WrongData("admin.index", "IndexData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h1 class=\"text-2xl font-semibold tracking-tight\">Dashboard</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<p class=\"text-muted-foreground mt-1 text-sm\">What is here, and what is waiting for you.</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</header>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<dl class=\"mt-8 grid gap-4 sm:grid-cols-2\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"card p-5\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-muted-foreground text-sm\">Published</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"mt-1 text-3xl font-semibold tabular-nums\">")
			}
			if err == nil {
//line resources/views/admin/index.kyse.go:35
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Published)))
//line resources/views/admin/index.go:78
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"card p-5\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-muted-foreground text-sm\">Drafts</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"mt-1 text-3xl font-semibold tabular-nums\">")
			}
			if err == nil {
//line resources/views/admin/index.kyse.go:39
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Drafts)))
//line resources/views/admin/index.go:98
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"card p-5\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-muted-foreground text-sm\">Comments</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"mt-1 text-3xl font-semibold tabular-nums\">")
			}
			if err == nil {
//line resources/views/admin/index.kyse.go:43
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Comments)))
//line resources/views/admin/index.go:118
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"card p-5\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dt class=\"text-muted-foreground text-sm\">Awaiting review</dt>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<dd class=\"mt-1 text-3xl font-semibold tabular-nums\">")
			}
			if err == nil {
//line resources/views/admin/index.kyse.go:50
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Waiting)))
//line resources/views/admin/index.go:141
			}
			if err == nil {
				_, err = io.WriteString(w, "</dd>\n")
			}
//line resources/views/admin/index.kyse.go:51
			if d.Waiting > 0 {
//line resources/views/admin/index.go:148
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<a class=\"btn mt-4\" data-size=\"sm\" href=\"")
				}
				if err == nil {
//line resources/views/admin/index.kyse.go:52
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CommentsURL())))
//line resources/views/admin/index.go:155
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Review them</a>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</dl>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "admin.layout", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
