// Code generated by `aru view:build` from layout.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package admin

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/admin/layout.kyse.go:7

// AdminLayout is what this layout asks of the screens inside it.
//
// It is view.Layout plus the sidebar, and declaring it here is the case the
// design leaves open: a layout renders with the interface it declares, and only
// falls back to view.Layout when it declares none. The public layout declares
// none, because the chrome the framework publishes is exactly what it draws.
//
// This one draws more, so it asks for more -- and asking through an interface
// rather than through Chrome directly is what would let a second admin screen
// with different data still fit.
type AdminLayout interface {
	view.Layout

	// On reports whether a sidebar item is the current one, and ItemClass
	// styles it. Two methods rather than one because the marked item is also
	// the one that gets aria-current, and a class string cannot carry that.
	On(item string) bool
	ItemClass(item string) string

	DashboardURL() string
	PostsURL() string
	CommentsURL() string
}

// Chrome is what every screen of the moderation area hands this layout.
//
// It is the area's own frame, not the public one: a sidebar instead of a
// navigation bar, and no theme picker, because somebody moderating comments is
// working rather than reading.
//
// Current is which item of the sidebar is the one you are on. It arrives as
// data rather than being worked out here by comparing paths -- the router knows
// it, and a template guessing at it is a template that gets it wrong the first
// time a path changes.
type Chrome struct {
	view.Page

	// Current is the sidebar item to mark, by its label.
	Current string

	// Where the sidebar points. They are fields, and the interface asks for
	// methods, so the three below are what bridges them -- a field and a method
	// cannot share a name in Go.
	Dashboard string
	Posts     string
	Comments  string
}

// DashboardURL, PostsURL and CommentsURL are where the sidebar points.
func (c Chrome) DashboardURL() string { return c.Dashboard }
func (c Chrome) PostsURL() string     { return c.Posts }
func (c Chrome) CommentsURL() string  { return c.Comments }

// Compile-time proof that this frame fits the layout above.
var _ AdminLayout = Chrome{}

// On reports whether an item is the current one.
func (c Chrome) On(item string) bool { return c.Current == item }

// ItemClass is the class of one sidebar item, marked or not.
func (c Chrome) ItemClass(item string) string {
	if c.On(item) {
		return "bg-accent text-accent-foreground rounded-md px-3 py-2 text-sm font-medium"
	}
	return "text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-md px-3 py-2 text-sm"
}

//line resources/views/admin/layout.go:84

func init() { view.RegisterLayout("admin.layout", renderAdminLayout) }

// renderAdminLayout renders the admin.layout layout.
func renderAdminLayout(w io.Writer, data any, sections map[string]func(io.Writer) error) error {
	d, ok := data.(AdminLayout)
	if !ok {
		return view.WrongData("admin.layout", "AdminLayout", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<!doctype html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<html lang=\"en\" class=\"h-full\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta charset=\"utf-8\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<title>")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:81
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
//line resources/views/admin/layout.go:117
	}
	if err == nil {
		_, err = io.WriteString(w, "</title>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"icon\" href=\"/favicon.ico\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"robots\" content=\"noindex, nofollow\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"stylesheet\" href=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:89
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("app.css"))))
//line resources/views/admin/layout.go:134
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:90
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("htmx.min.js"))))
//line resources/views/admin/layout.go:145
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:91
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("alpine.min.js"))))
//line resources/views/admin/layout.go:156
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:92
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("basecoat.bundle.js"))))
//line resources/views/admin/layout.go:167
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:93
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("theme.js"))))
//line resources/views/admin/layout.go:178
	}
	if err == nil {
		_, err = io.WriteString(w, "\"></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<body hx-boost=\"true\" hx-headers='{\"X-CSRF-Token\": \"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:95
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CSRFToken())))
//line resources/views/admin/layout.go:192
	}
	if err == nil {
		_, err = io.WriteString(w, "\"}' class=\"bg-background text-foreground min-h-full antialiased\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div class=\"flex min-h-full\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<aside class=\"bg-sidebar text-sidebar-foreground hidden w-64 shrink-0 border-r p-4 sm:block\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<a class=\"block px-3 py-2 text-sm font-semibold tracking-tight\" href=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:98
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.HomeLink())))
//line resources/views/admin/layout.go:209
	}
	if err == nil {
		_, err = io.WriteString(w, "\">")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:98
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.BrandName())))
//line resources/views/admin/layout.go:217
	}
	if err == nil {
		_, err = io.WriteString(w, "</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<nav class=\"mt-6 flex flex-col gap-1\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t<a class=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:101
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.ItemClass("Dashboard"))))
//line resources/views/admin/layout.go:231
	}
	if err == nil {
		_, err = io.WriteString(w, "\" href=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:101
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.DashboardURL())))
//line resources/views/admin/layout.go:239
	}
	if err == nil {
		_, err = io.WriteString(w, "\">Dashboard</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t<a class=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:102
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.ItemClass("Comments"))))
//line resources/views/admin/layout.go:250
	}
	if err == nil {
		_, err = io.WriteString(w, "\" href=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:102
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CommentsURL())))
//line resources/views/admin/layout.go:258
	}
	if err == nil {
		_, err = io.WriteString(w, "\">Comments</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t<a class=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:103
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.ItemClass("Posts"))))
//line resources/views/admin/layout.go:269
	}
	if err == nil {
		_, err = io.WriteString(w, "\" href=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:103
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PostsURL())))
//line resources/views/admin/layout.go:277
	}
	if err == nil {
		_, err = io.WriteString(w, "\">Posts</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t</nav>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<form class=\"mt-6\" method=\"post\" action=\"")
	}
	if err == nil {
//line resources/views/admin/layout.kyse.go:106
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LogoutLink())))
//line resources/views/admin/layout.go:291
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		err = view.CSRF(w, data)
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t<button type=\"submit\" class=\"btn w-full\" data-variant=\"outline\" data-size=\"sm\">Sign out</button>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t</form>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</aside>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<main class=\"min-w-0 flex-1 px-6 py-10\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<div class=\"mx-auto w-full max-w-3xl\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "content")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</main>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div id=\"toaster\" class=\"toaster\" aria-live=\"polite\"></div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</body>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</html>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
