// Code generated by `aru view:build` from create.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package comments

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

//line resources/views/comments/create.kyse.go:11

// CommentsCreateData is what CommentController.Create hands this page, and what
// Store hands it back when the submission was rejected: same view, same data,
// with the messages filled in.
type CommentsCreateData struct {
	// Page is the state the layout draws. Its Token is what @csrf writes into
	// the hidden field, through Page.CSRFToken -- it comes from the page data
	// rather than from a global, because a template that reaches for request
	// state outside the data it was given is how a form ends up carrying
	// another session's token under load.
	view.Page
	// Form is what was typed, so a rejected submission comes back filled in.
	Form CommentForm
	// Errors is the message per field, as validation produced it.
	Errors map[string][]string
}

// FieldError is the first message for a field, or empty.
//
// A method rather than a lookup in the markup: a view that indexes a map has to
// check the length first, and d.Errors["title"][0] without that check panics
// on the happy path -- which is the request where nothing was wrong.
func (d CommentsCreateData) FieldError(field string) string {
	if msgs := d.Errors[field]; len(msgs) > 0 {
		return msgs[0]
	}
	return ""
}

// Compile-time proof that this page fits the layout it extends.
var _ view.Layout = CommentsCreateData{}

// CommentForm is the form as text, which is what a form carries.
//
// The value that comes back after a rejection is exactly what was typed,
// including the number that failed to parse -- retyping a whole form because one
// field was wrong is how a screen becomes unpleasant.
type CommentForm struct {
	// ID is empty on creation and set on edit, where it addresses the record.
	ID string
	// PostId is the Post id input.
	PostId string
	// Author is the Author input.
	Author string
	// Body is the Body input.
	Body string
	// Approved is the Approved input.
	Approved bool
}

// ApprovedAttr renders the checked attribute of the Approved checkbox.
func (f CommentForm) ApprovedAttr() string {
	if f.Approved {
		return "checked"
	}
	return ""
}

// arandu:begin custom
// Anything else these forms need in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/comments/create.go:79

func init() { view.Register("comments.create", renderCommentsCreate) }

// renderCommentsCreate renders comments.create.
func renderCommentsCreate(w io.Writer, data any) error {
	d, ok := data.(CommentsCreateData)
	if !ok {
		return view.WrongData("comments.create", "CommentsCreateData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<nav class=\"text-sm text-slate-500 dark:text-slate-400\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"underline underline-offset-2 hover:text-slate-900 dark:hover:text-slate-100\" href=\"/comments\">Comments</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</nav>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"mt-2 text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/comments/create.kyse.go:81
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/comments/create.go:111
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<form class=\"mt-8 space-y-6\" method=\"post\" action=\"/comments\" hx-post=\"/comments\" hx-target=\"this\" hx-swap=\"outerHTML\">\n")
			}
			if err == nil {
				err = view.CSRF(w, data)
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/comments/create.kyse.go:86
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "post_id", Label: "Post id", Type: "text", Value: d.Form.PostId, Error: d.FieldError("post_id"), Required: true})))
//line resources/views/comments/create.go:134
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/comments/create.kyse.go:95
				_, err = io.WriteString(w, view.Text(components.Field(components.FieldProps{Name: "author", Label: "Author", Type: "text", Value: d.Form.Author, Error: d.FieldError("author"), Required: true})))
//line resources/views/comments/create.go:148
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t")
			}
			if err == nil {
//line resources/views/comments/create.kyse.go:104
				_, err = io.WriteString(w, view.Text(components.Textarea(components.TextareaProps{Name: "body", Label: "Body", Value: d.Form.Body, Error: d.FieldError("body"), Rows: 6, Required: true})))
//line resources/views/comments/create.go:162
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<label class=\"flex items-center gap-2 text-sm\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<input class=\"input\" id=\"approved\" name=\"approved\" type=\"checkbox\" value=\"1\" ")
			}
			if err == nil {
//line resources/views/comments/create.kyse.go:114
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Form.ApprovedAttr())))
//line resources/views/comments/create.go:179
			}
			if err == nil {
				_, err = io.WriteString(w, ">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\tApproved\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</label>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<div class=\"flex items-center gap-3\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<button class=\"rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-slate-300\" type=\"submit\">Save</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<a class=\"text-sm text-slate-500 underline underline-offset-2 dark:text-slate-400\" href=\"/comments\">Cancel</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</form>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
