// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package comments

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/comments/index.kyse.go:7

// CommentsIndexData is what CommentController.Index hands this page.
type CommentsIndexData struct {
	// view.Page is the chrome the layout draws: the title, the description, the
	// CSRF token and the navigation. Embedded rather than repeated, and what
	// makes this struct fit the layout.
	view.Page
	// Comments is the page of records.
	Comments []CommentRow
	// NextCursor is the keyset cursor of the following page. It is empty on the
	// last page, and the link is not rendered then.
	NextCursor string
}

// Compile-time proof that this page fits the layout it extends.
var _ view.Layout = CommentsIndexData{}

// CommentRow is one record, formatted for display by the controller.
type CommentRow struct {
	// ID is what the row links to.
	ID string
	// PostId is the Post id column.
	PostId string
	// Author is the Author column.
	Author string
	// Body is the Body column.
	Body string
	// Approved is the Approved column.
	Approved bool
	// Created is the creation timestamp, already formatted.
	Created string
}

// arandu:begin custom
// Anything else these pages need in Go goes here, and survives regeneration.
// arandu:end custom

//line resources/views/comments/index.go:53

func init() { view.Register("comments.index", renderCommentsIndex) }

// renderCommentsIndex renders comments.index.
func renderCommentsIndex(w io.Writer, data any) error {
	d, ok := data.(CommentsIndexData)
	if !ok {
		return view.WrongData("comments.index", "CommentsIndexData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<div class=\"flex items-center justify-between gap-4\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<h1 class=\"text-3xl font-semibold tracking-tight\">")
			}
			if err == nil {
//line resources/views/comments/index.kyse.go:49
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line resources/views/comments/index.go:76
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<a class=\"rounded-md border border-slate-300 px-3 py-2 text-sm font-medium hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-900\" href=\"/comments/create\">New comment</a>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/comments/index.kyse.go:53
			if len(d.Comments) == 0 {
//line resources/views/comments/index.go:92
				if err == nil {
					_, err = io.WriteString(w, "\t\t<p class=\"mt-8 text-sm text-slate-500 dark:text-slate-400\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\tNo comment yet. <a class=\"underline underline-offset-2\" href=\"/comments/create\">Add the first one</a>.\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</p>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/comments/index.kyse.go:59
			if len(d.Comments) > 0 {
//line resources/views/comments/index.go:108
				if err == nil {
					_, err = io.WriteString(w, "\t\t<div class=\"mt-8 overflow-x-auto\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<table class=\"w-full border-collapse text-left text-sm\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<thead class=\"border-b border-slate-200 text-slate-500 dark:border-slate-800 dark:text-slate-400\">\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t<tr>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Post id</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Author</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Body</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t<th class=\"py-2 pr-4 font-medium\">Approved</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t<th class=\"py-2 font-medium\">Created</th>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t</tr>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t</thead>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<tbody>\n")
				}
//line resources/views/comments/index.kyse.go:72
				for _, comment := range d.Comments {
					_ = comment
//line resources/views/comments/index.go:148
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t<tr class=\"border-b border-slate-100 dark:border-slate-900\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t<td class=\"py-2 pr-4\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t<a class=\"font-medium underline underline-offset-2\" href=\"/comments/")
					}
					if err == nil {
//line resources/views/comments/index.kyse.go:75
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.ID)))
//line resources/views/comments/index.go:161
					}
					if err == nil {
						_, err = io.WriteString(w, "\">")
					}
					if err == nil {
//line resources/views/comments/index.kyse.go:75
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.PostId)))
//line resources/views/comments/index.go:169
					}
					if err == nil {
						_, err = io.WriteString(w, "</a>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"py-2 pr-4\">")
					}
					if err == nil {
//line resources/views/comments/index.kyse.go:77
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Author)))
//line resources/views/comments/index.go:183
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 pr-4\">")
					}
					if err == nil {
//line resources/views/comments/index.kyse.go:78
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Body)))
//line resources/views/comments/index.go:194
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<td class=\"py-2 pr-4\">")
					}
					if err == nil {
//line resources/views/comments/index.kyse.go:79
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Approved)))
//line resources/views/comments/index.go:205
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t<td class=\"py-2 text-slate-500 dark:text-slate-400\">")
					}
					if err == nil {
//line resources/views/comments/index.kyse.go:80
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(comment.Created)))
//line resources/views/comments/index.go:216
					}
					if err == nil {
						_, err = io.WriteString(w, "</td>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t</tr>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t</tbody>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t</table>\n")
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</div>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/comments/index.kyse.go:88
			if d.NextCursor != "" {
//line resources/views/comments/index.go:240
				if err == nil {
					_, err = io.WriteString(w, "\t\t<a class=\"mt-6 inline-block text-sm underline underline-offset-2\" href=\"/comments?cursor=")
				}
				if err == nil {
//line resources/views/comments/index.kyse.go:89
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.NextCursor)))
//line resources/views/comments/index.go:247
				}
				if err == nil {
					_, err = io.WriteString(w, "\">Next page</a>\n")
				}
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
