package migrations

import (
	"context"

	"github.com/arandu-io/hesape/database/migrations"
)

// createCommentsTable creates the comments table.
//
// It is unexported and listed in All(), which is what the kernel collects: a
// migration nobody lists is a migration nobody applies, and the compiler says so
// here rather than the schema saying so in production.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one id -- alter it with a new migration instead.
//
// Every type below spells the same in SQLite, PostgreSQL and MySQL, so one
// schema serves all three. Anything a key or an index names is VARCHAR rather
// than TEXT, because MySQL refuses TEXT in a key without a prefix length. The id
// is generated by the application: gen_random_uuid, UUID() and randomblob are
// three spellings of one idea.
type createCommentsTable struct{ migrations.BaseMigration }

// Down is found by a type assertion when a rollback runs, so one with the
// wrong signature would apply fine and simply never be reversed. This is the
// line that turns that into a build failure.
var _ migrations.ReversibleMigration = createCommentsTable{}

// GetName is this migration's identity. The date prefix carries the order.
func (createCommentsTable) GetName() string { return "2026_08_08_000002_create_comments_table" }

// Up creates the table, then the index the listing reads.
func (createCommentsTable) Up(ctx context.Context, conn migrations.Connection) error {
	if _, err := conn.Statement(ctx, `CREATE TABLE comments (
		id         VARCHAR(255) PRIMARY KEY,
		post_id    VARCHAR(255) NOT NULL,
		author     VARCHAR(255) NOT NULL,
		body       TEXT NOT NULL,
		approved   BOOLEAN,
		created_at TIMESTAMP NOT NULL
	)`, nil); err != nil {
		return err
	}

	_, err := conn.Statement(ctx, `CREATE INDEX comments_created_idx ON comments (created_at, id)`, nil)
	return err
}

// Down drops the table, and the index goes with it on all three engines.
func (createCommentsTable) Down(ctx context.Context, conn migrations.Connection) error {
	_, err := conn.Statement(ctx, `DROP TABLE comments`, nil)
	return err
}
