package migrations

import (
	"context"

	"github.com/arandu-io/hesape/database/migrations"
)

// createPostsTable creates the posts table.
//
// It is unexported and listed in All(), which is what the kernel collects: a
// migration nobody lists is a migration nobody applies, and the compiler says so
// here rather than the schema saying so in production.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one id -- alter it with a new migration instead.
//
// Every type below spells the same in SQLite, PostgreSQL and MySQL, so one
// schema serves all three. Anything a key or an index names is VARCHAR rather
// than TEXT, because MySQL refuses TEXT in a key without a prefix length. The id
// is generated by the application: gen_random_uuid, UUID() and randomblob are
// three spellings of one idea.
//
// It embeds BaseMigration, which answers the half that is the same for every
// migration: the default connection, a guard that always lets it run, and a
// transaction around it wherever the engine offers one.
type createPostsTable struct{ migrations.BaseMigration }

// Down is found by a type assertion when a rollback runs, so one with the
// wrong signature would apply fine and simply never be reversed. This is the
// line that turns that into a build failure.
var _ migrations.ReversibleMigration = createPostsTable{}

// GetName is this migration's identity. The date prefix carries the order.
func (createPostsTable) GetName() string { return "2026_08_08_000001_create_posts_table" }

// Up creates the table, then the index the listing reads.
//
// Two statements are two calls. A statement is what the driver is handed, and
// several of them in one string is a thing each engine decides for itself --
// SQLite runs them, PostgreSQL runs them only outside a prepared statement, and
// MySQL refuses unless the connection was opened asking for it.
func (createPostsTable) Up(ctx context.Context, conn migrations.Connection) error {
	if _, err := conn.Statement(ctx, `CREATE TABLE posts (
		id           VARCHAR(255) PRIMARY KEY,
		title        VARCHAR(255) NOT NULL,
		slug         VARCHAR(255) NOT NULL,
		body         TEXT NOT NULL,
		published_at TIMESTAMP,
		created_at   TIMESTAMP NOT NULL,
		UNIQUE (slug)
	)`, nil); err != nil {
		return err
	}

	_, err := conn.Statement(ctx, `CREATE INDEX posts_created_idx ON posts (created_at, id)`, nil)
	return err
}

// Down drops the table, and the index goes with it on all three engines.
func (createPostsTable) Down(ctx context.Context, conn migrations.Connection) error {
	_, err := conn.Statement(ctx, `DROP TABLE posts`, nil)
	return err
}
