package migrations

import (
	"context"

	"github.com/arandu-io/hesape/database/migrations"
	"github.com/arandu-io/hesape/database/schema"
)

func init() { migrations.Register(createPostsTable{}) }

// createPostsTable creates the posts table.
//
// It is unexported and listed in All(), which is what the kernel collects: a
// migration nobody lists is a migration nobody applies, and the compiler says so
// here rather than the schema saying so in production.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one id -- alter it with a new migration instead.
//
// Every type below spells the same in SQLite, PostgreSQL and MySQL, so one
// schema serves all three. Anything a key or an index names is VARCHAR rather
// than TEXT, because MySQL refuses TEXT in a key without a prefix length. The id
// is generated by the application: gen_random_uuid, UUID() and randomblob are
// three spellings of one idea.
//
// It embeds BaseMigration, which answers the half that is the same for every
// migration: the default connection, a guard that always lets it run, and a
// transaction around it wherever the engine offers one.
type createPostsTable struct{ migrations.BaseMigration }

// Down is found by a type assertion when a rollback runs, so one with the
// wrong signature would apply fine and simply never be reversed. This is the
// line that turns that into a build failure.
var _ migrations.ReversibleMigration = createPostsTable{}

// GetName is this migration's identity. The date prefix carries the order.
func (createPostsTable) GetName() string { return "2026_08_08_000001_create_posts_table" }

// Up creates the table and the index the listing reads.
//
// The column types are the Blueprint's to spell, one per engine. This migration
// used to write them, with a comment above explaining that anything a key names
// has to be VARCHAR because MySQL refuses TEXT in a key without a prefix length
// -- which is what the grammar knows, worked out by hand here instead.
//
// conn.Statement is still reachable, and the backfill next door uses it. What it
// is for is what no Blueprint reaches.
func (createPostsTable) Up(ctx context.Context, conn migrations.Connection) error {
	return conn.Schema().Create(ctx, "posts", func(table *schema.Blueprint) {
		table.String("id").Primary()
		table.String("title")
		table.String("slug").Unique()
		table.Text("body")
		table.Timestamp("published_at").Nullable()
		table.Timestamp("created_at")

		table.Index([]string{"created_at", "id"})
	})
}

// Down drops the table, and the index goes with it on all three engines.
func (createPostsTable) Down(ctx context.Context, conn migrations.Connection) error {
	return conn.Schema().DropIfExists(ctx, "posts")
}
