package migrations

import "github.com/arandu-io/framework/kernel"

// createCategoriesTable creates the categories table.
//
// It is unexported and listed in All(), which is what the kernel collects: a
// migration nobody lists is a migration nobody applies, and the compiler says so
// here rather than the schema saying so in production.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one id -- alter it with a new migration instead (RULE 16).
//
// Every type below spells the same in SQLite, PostgreSQL and MySQL, so one
// schema serves all three. Anything a key or an index names is VARCHAR rather
// than TEXT, because MySQL refuses TEXT in a key without a prefix length. The id
// is generated by the application: gen_random_uuid, UUID() and randomblob are
// three spellings of one idea.
var createCategoriesTable = kernel.Migration{
	ID: "2026_08_09_000002_create_categories_table",
	Up: `CREATE TABLE categories (
		id         VARCHAR(255) PRIMARY KEY,
		name	VARCHAR(255) NOT NULL,
		slug	VARCHAR(255) NOT NULL,
		description	TEXT,
		created_at TIMESTAMP NOT NULL
	);
	CREATE INDEX categories_created_idx ON categories (created_at, id);`,
	Down: `DROP TABLE categories;`,
}
