package migrations

import (
	"context"

	"github.com/arandu-io/hesape/database/migrations"
)

// createCategoriesTable creates the categories table.
//
// It is unexported and listed in All(), which is what the kernel collects: a
// migration nobody lists is a migration nobody applies, and the compiler says so
// here rather than the schema saying so in production.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one id -- alter it with a new migration instead.
//
// Every type below spells the same in SQLite, PostgreSQL and MySQL, so one
// schema serves all three. Anything a key or an index names is VARCHAR rather
// than TEXT, because MySQL refuses TEXT in a key without a prefix length. The id
// is generated by the application: gen_random_uuid, UUID() and randomblob are
// three spellings of one idea.
type createCategoriesTable struct{ migrations.BaseMigration }

// Down is found by a type assertion when a rollback runs, so one with the
// wrong signature would apply fine and simply never be reversed. This is the
// line that turns that into a build failure.
var _ migrations.ReversibleMigration = createCategoriesTable{}

// GetName is this migration's identity. The date prefix carries the order.
func (createCategoriesTable) GetName() string { return "2026_08_09_000002_create_categories_table" }

// Up creates the table, then the index the listing reads.
func (createCategoriesTable) Up(ctx context.Context, conn migrations.Connection) error {
	if _, err := conn.Statement(ctx, `CREATE TABLE categories (
		id          VARCHAR(255) PRIMARY KEY,
		name        VARCHAR(255) NOT NULL,
		slug        VARCHAR(255) NOT NULL,
		description TEXT,
		created_at  TIMESTAMP NOT NULL
	)`, nil); err != nil {
		return err
	}

	_, err := conn.Statement(ctx, `CREATE INDEX categories_created_idx ON categories (created_at, id)`, nil)
	return err
}

// Down drops the table, and the index goes with it on all three engines.
func (createCategoriesTable) Down(ctx context.Context, conn migrations.Connection) error {
	_, err := conn.Statement(ctx, `DROP TABLE categories`, nil)
	return err
}
