package migrations

import (
	"context"

	"github.com/arandu-io/hesape/database/migrations"
	"github.com/arandu-io/hesape/database/schema"
)

func init() { migrations.Register(createCategoriesTable{}) }

// createCategoriesTable creates the categories table.
//
// It is unexported and listed in All(), which is what the kernel collects: a
// migration nobody lists is a migration nobody applies, and the compiler says so
// here rather than the schema saying so in production.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one id -- alter it with a new migration instead.
//
// Every type below spells the same in SQLite, PostgreSQL and MySQL, so one
// schema serves all three. Anything a key or an index names is VARCHAR rather
// than TEXT, because MySQL refuses TEXT in a key without a prefix length. The id
// is generated by the application: gen_random_uuid, UUID() and randomblob are
// three spellings of one idea.
type createCategoriesTable struct{ migrations.BaseMigration }

// Down is found by a type assertion when a rollback runs, so one with the
// wrong signature would apply fine and simply never be reversed. This is the
// line that turns that into a build failure.
var _ migrations.ReversibleMigration = createCategoriesTable{}

// GetName is this migration's identity. The date prefix carries the order.
func (createCategoriesTable) GetName() string { return "2026_08_09_000002_create_categories_table" }

// Up creates the table, then the index the listing reads.
func (createCategoriesTable) Up(ctx context.Context, conn migrations.Connection) error {
	return conn.Schema().Create(ctx, "categories", func(table *schema.Blueprint) {
		table.String("id").Primary()
		table.String("name")
		table.String("slug")
		table.Text("description").Nullable()
		table.Timestamp("created_at")

		table.Index([]string{"created_at", "id"})
	})
}

// Down drops the table, and the index goes with it on all three engines.
func (createCategoriesTable) Down(ctx context.Context, conn migrations.Connection) error {
	return conn.Schema().DropIfExists(ctx, "categories")
}
