// Code generated by `aru font:add`. DO NOT EDIT.
//
// The vendored faces, embedded and handed to the view layer, which serves them
// content-addressed under /_arandu/assets/<hash>/. resources/css/fonts.css
// references them by bare file name, and a relative url() in a stylesheet
// served from that directory resolves to exactly this.
//
// It is committed for the same reason assets/app.css is: `go build` has to
// work on a fresh clone, before any tool has run.

package assets

import (
	_ "embed"

	"github.com/arandu-io/framework/view"
)

//go:embed fonts/young-serif-400-latin.woff2
var display0 []byte

func init() {
	view.RegisterFont("young-serif-400-latin.woff2", display0)
}
