// Code generated by `aru font:add`. DO NOT EDIT.
//
// The vendored faces, embedded and handed to kyse, which serves them
// content-addressed under /_arandu/assets/<hash>/. resources/css/fonts.css
// references each by that exact URL -- its own content hash, not the
// stylesheet's, because a mismatch is served uncached on purpose.
//
// It is committed for the same reason assets/app.css is: `go build` has to
// work on a fresh clone, before any tool has run.

package assets

import (
	_ "embed"

	"github.com/arandu-io/kyse/fonts"
)

//go:embed fonts/montserrat-400-800-latin.woff2
var display0 []byte

func init() {
	fonts.Register("montserrat-400-800-latin.woff2", display0)
}
