// Package customer is the canonical module of this example: the shape every
// module generated by `aru make:module` will have.
//
// Files of a module (vertical layout, one directory per feature, not one
// directory per layer):
//
//	module.go            registration, routes, migrations, health
//	customer.entity.go   the entity, and what it refuses to reveal
//	customer.policy.go   who may do what; denies by default
//	customer.repo.go     data access, requires a Grant
//	customer.service.go  business rules; Authorize -> Grant -> Repository
//	customer.request.go  input types and Validate
//	handlers.go          thin: extract, delegate, render
//
// The consequence of this layout is that a module is publishable. A directory is
// a unit of distribution; thirty files spread across six directories are not.
package customer

import (
	"context"
	"net/http"

	"github.com/arandu-io/framework/httpx"
	"github.com/arandu-io/framework/kernel"
	"github.com/arandu-io/framework/security"
)

// Module registers the customer routes.
type Module struct {
	svc     *Service
	subject SubjectResolver
}

// SubjectResolver returns who is acting.
//
// It reads the session, and that is the only acceptable source: a subject taken
// from the request body is the client telling the server what it is allowed to
// do. The application provides this function, so the module never has to know
// how sessions are stored.
type SubjectResolver func(r *http.Request) (security.Subject, error)

// New returns the module.
func New(svc *Service, subject SubjectResolver) *Module {
	return &Module{svc: svc, subject: subject}
}

// Compile-time proof that the module honors the kernel contracts it claims.
var (
	_ kernel.Module     = (*Module)(nil)
	_ kernel.Migratable = (*Module)(nil)
	_ kernel.Health     = (*Module)(nil)
)

// Name is the module identifier.
func (m *Module) Name() string { return "customer" }

// Routes registers the module's routes.
func (m *Module) Routes(r *httpx.Router) {
	g := r.Group("/customers")
	g.Get("/", m.list)
	g.Post("/", m.create)
	g.Get("/{id}", m.show)
	g.Get("/{id}/document", m.showDocument)
	g.Delete("/{id}", m.destroy)
}

// Health reports whether the module can reach its storage.
func (m *Module) Health(ctx context.Context) error {
	return m.svc.repo.db.PingContext(ctx)
}

// Migrations declares the schema this module owns.
//
// Every type here spells the same in SQLite, PostgreSQL and MySQL, which is what
// lets one project develop on a file and deploy on Postgres with one schema. The
// index exists because List orders by (created_at, id) -- an index that matches
// the query the code actually issues, rather than one added after the first slow
// page.
func (m *Module) Migrations() []kernel.Migration {
	return []kernel.Migration{{
		ID: "2026_07_31_000001_create_customers_table",
		Up: `CREATE TABLE customers (
			id         TEXT PRIMARY KEY,
			tenant_id  TEXT NOT NULL,
			name       TEXT NOT NULL,
			email      TEXT NOT NULL,
			document   TEXT NOT NULL,
			created_at TIMESTAMP NOT NULL,
			UNIQUE (tenant_id, email)
		);
		CREATE INDEX customers_tenant_created_idx ON customers (tenant_id, created_at, id);`,
		Down: `DROP TABLE customers;`,
	}}
}
