// Code generated by aru model:build from Category.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Categories starts a query on the table of Category, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Categories(db model.DB) *CategoryQuery { return &CategoryQuery{b: categoryTable.Query(db)} }

// CategoryQuery is a query on the table of Category.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Category rows or a value; there is
// no way to run one without a Grant.
type CategoryQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of Category.go -- and for the
// factory, which builds rows through it.
func (q *CategoryQuery) Base() *model.Builder { return q.b }

// New returns an empty Category on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *CategoryQuery) New() (*Category, error) {
	e, err := q.b.NewModelInstance(nil)
	return categoryOf(e), err
}

// CategoryCollection is rows of Category, as a query returns them.
type CategoryCollection []*Category

// CategoryCollectionOf converts rows of the table of Category. A nil input is a nil
// collection.
func CategoryCollectionOf(rows model.Rows) CategoryCollection {
	if rows == nil {
		return nil
	}
	out := make(CategoryCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Category)
	}
	return out
}

func categoryOf(e model.Entity) *Category {
	row, _ := e.(*Category)
	return row
}

// categoryColumn turns a closure over CategoryQuery into one over the core builder, so
// passing func(*CategoryQuery) where a column goes adds a parenthesised group.
func categoryColumn(column any) any {
	if group, ok := column.(func(*CategoryQuery)); ok {
		return func(b *model.Builder) { group(&CategoryQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *CategoryQuery) Clone() *CategoryQuery { return &CategoryQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*CategoryQuery) in place of the column adds a group.
func (q *CategoryQuery) Where(column any, args ...any) *CategoryQuery {
	q.b.Where(categoryColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*CategoryQuery) in place of the column adds a group.
func (q *CategoryQuery) OrWhere(column any, args ...any) *CategoryQuery {
	q.b.OrWhere(categoryColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *CategoryQuery) WhereNot(column any, args ...any) *CategoryQuery {
	q.b.WhereNot(categoryColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *CategoryQuery) OrWhereNot(column any, args ...any) *CategoryQuery {
	q.b.OrWhereNot(categoryColumn(column), args...)
	return q
}

func (q *CategoryQuery) WhereIn(column any, values []any) *CategoryQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *CategoryQuery) WhereNotIn(column any, values []any) *CategoryQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *CategoryQuery) WhereNull(columns ...any) *CategoryQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *CategoryQuery) WhereNotNull(columns ...any) *CategoryQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *CategoryQuery) WhereBetween(column any, from, to any) *CategoryQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *CategoryQuery) WhereColumn(first any, args ...any) *CategoryQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *CategoryQuery) WhereKey(id any) *CategoryQuery {
	q.b.WhereKey(id)
	return q
}

func (q *CategoryQuery) WhereExists(callback func(*query.Builder)) *CategoryQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *CategoryQuery) WhereNotExists(callback func(*query.Builder)) *CategoryQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *CategoryQuery) WhereHas(relation string, callback func(*query.Builder)) *CategoryQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *CategoryQuery) OrWhereHas(relation string, callback func(*query.Builder)) *CategoryQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *CategoryQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *CategoryQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *CategoryQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *CategoryQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *CategoryQuery) WhereRelation(relation string, column any, args ...any) *CategoryQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *CategoryQuery) OrWhereRelation(relation string, column any, args ...any) *CategoryQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *CategoryQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *CategoryQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *CategoryQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *CategoryQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *CategoryQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *CategoryQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *CategoryQuery) OrHas(relation, operator string, count int) *CategoryQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *CategoryQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *CategoryQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *CategoryQuery) OrDoesntHave(relation string) *CategoryQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *CategoryQuery) Select(columns ...any) *CategoryQuery {
	q.b.Select(columns...)
	return q
}

func (q *CategoryQuery) AddSelect(columns ...any) *CategoryQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *CategoryQuery) SelectRaw(expression string, bindings ...any) *CategoryQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *CategoryQuery) Join(table any, first any, args ...any) *CategoryQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *CategoryQuery) GroupBy(groups ...any) *CategoryQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *CategoryQuery) OrderBy(column any, direction ...string) *CategoryQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *CategoryQuery) OrderByDesc(column any) *CategoryQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *CategoryQuery) Latest(column ...string) *CategoryQuery {
	q.b.Latest(column...)
	return q
}

func (q *CategoryQuery) Oldest(column ...string) *CategoryQuery {
	q.b.Oldest(column...)
	return q
}

func (q *CategoryQuery) Limit(value int) *CategoryQuery {
	q.b.Limit(value)
	return q
}

func (q *CategoryQuery) Offset(value int) *CategoryQuery {
	q.b.Offset(value)
	return q
}

func (q *CategoryQuery) ForPage(page, perPage int) *CategoryQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *CategoryQuery) With(relations ...string) *CategoryQuery {
	q.b.With(relations...)
	return q
}

func (q *CategoryQuery) WithCount(relations ...string) *CategoryQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *CategoryQuery) WithExists(relation string) *CategoryQuery {
	q.b.WithExists(relation)
	return q
}

func (q *CategoryQuery) WithSum(relation, column string) *CategoryQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *CategoryQuery) WithAvg(relation, column string) *CategoryQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *CategoryQuery) WithMin(relation, column string) *CategoryQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *CategoryQuery) WithMax(relation, column string) *CategoryQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *CategoryQuery) Without(relations ...string) *CategoryQuery {
	q.b.Without(relations...)
	return q
}

func (q *CategoryQuery) WithoutGlobalScope(identifier string) *CategoryQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *CategoryQuery) WithoutGlobalScopes(identifiers ...string) *CategoryQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *CategoryQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (CategoryCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return CategoryCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *CategoryQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Category, error) {
	e, err := q.b.First(ctx, g, columns...)
	return categoryOf(e), err
}

func (q *CategoryQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Category, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return categoryOf(e), err
}

func (q *CategoryQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Category, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return categoryOf(e), err
}

func (q *CategoryQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Category, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return categoryOf(e), err
}

func (q *CategoryQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Category, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return categoryOf(e), err
}

func (q *CategoryQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Category, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return categoryOf(e), err
}

func (q *CategoryQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Category, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return categoryOf(e), err
}

func (q *CategoryQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Category, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return categoryOf(e), err
}

func (q *CategoryQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (CategoryCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return CategoryCollectionOf(rows), err
}

func (q *CategoryQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Category, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return categoryOf(e), err
}

func (q *CategoryQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Category, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return categoryOf(e), err
}

func (q *CategoryQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Category, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return categoryOf(e), err
}

func (q *CategoryQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Category, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return categoryOf(e), err
}

func (q *CategoryQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (CategoryCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return CategoryCollectionOf(rows), meta, err
}

func (q *CategoryQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (CategoryCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return CategoryCollectionOf(rows), meta, err
}

func (q *CategoryQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (CategoryCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return CategoryCollectionOf(rows), meta, err
}

func (q *CategoryQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(CategoryCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(CategoryCollectionOf(rows), page)
	})
}

func (q *CategoryQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Category, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(categoryOf(e), index)
	})
}

func (q *CategoryQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Category, error] {
	return func(yield func(*Category, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(categoryOf(e), err) {
				return
			}
		}
	}
}

func (q *CategoryQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *CategoryQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *CategoryQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *CategoryQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *CategoryQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *CategoryQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *CategoryQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *CategoryQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *CategoryQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *CategoryQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *CategoryQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *CategoryQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *CategoryQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *CategoryQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *CategoryQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *CategoryQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *CategoryQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *CategoryQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *CategoryQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c CategoryCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c CategoryCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c CategoryCollection) Find(key any) *Category { return categoryOf(c.Rows().Find(key)) }

func (c CategoryCollection) FindOrFail(key any) (*Category, error) {
	e, err := c.Rows().FindOrFail(key)
	return categoryOf(e), err
}

func (c CategoryCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c CategoryCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c CategoryCollection) Only(keys ...any) CategoryCollection {
	return CategoryCollectionOf(c.Rows().Only(keys...))
}

func (c CategoryCollection) Except(keys ...any) CategoryCollection {
	return CategoryCollectionOf(c.Rows().Except(keys...))
}

func (c CategoryCollection) Unique() CategoryCollection {
	return CategoryCollectionOf(c.Rows().Unique())
}

func (c CategoryCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c CategoryCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c CategoryCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c CategoryCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (CategoryCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return CategoryCollectionOf(rows), err
}

func (c CategoryCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Category; it shadows the untyped one the
// embedded model promotes.
func (row *Category) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Category, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return categoryOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Category) Replicate(except ...string) (*Category, error) {
	e, err := row.Model.Replicate(except...)
	return categoryOf(e), err
}
