// Code generated by aru model:build from Post.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Posts starts a query on the table of Post, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Posts(db model.DB) *PostQuery { return &PostQuery{b: postTable.Query(db)} }

// PostQuery is a query on the table of Post.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Post rows or a value; there is
// no way to run one without a Grant.
type PostQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of Post.go -- and for the
// factory, which builds rows through it.
func (q *PostQuery) Base() *model.Builder { return q.b }

// New returns an empty Post on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *PostQuery) New() (*Post, error) {
	e, err := q.b.NewModelInstance(nil)
	return postOf(e), err
}

// PostCollection is rows of Post, as a query returns them.
type PostCollection []*Post

// PostCollectionOf converts rows of the table of Post. A nil input is a nil
// collection.
func PostCollectionOf(rows model.Rows) PostCollection {
	if rows == nil {
		return nil
	}
	out := make(PostCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Post)
	}
	return out
}

func postOf(e model.Entity) *Post {
	row, _ := e.(*Post)
	return row
}

// postColumn turns a closure over PostQuery into one over the core builder, so
// passing func(*PostQuery) where a column goes adds a parenthesised group.
func postColumn(column any) any {
	if group, ok := column.(func(*PostQuery)); ok {
		return func(b *model.Builder) { group(&PostQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *PostQuery) Clone() *PostQuery { return &PostQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*PostQuery) in place of the column adds a group.
func (q *PostQuery) Where(column any, args ...any) *PostQuery {
	q.b.Where(postColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*PostQuery) in place of the column adds a group.
func (q *PostQuery) OrWhere(column any, args ...any) *PostQuery {
	q.b.OrWhere(postColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *PostQuery) WhereNot(column any, args ...any) *PostQuery {
	q.b.WhereNot(postColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *PostQuery) OrWhereNot(column any, args ...any) *PostQuery {
	q.b.OrWhereNot(postColumn(column), args...)
	return q
}

func (q *PostQuery) WhereIn(column any, values []any) *PostQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *PostQuery) WhereNotIn(column any, values []any) *PostQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *PostQuery) WhereNull(columns ...any) *PostQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *PostQuery) WhereNotNull(columns ...any) *PostQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *PostQuery) WhereBetween(column any, from, to any) *PostQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *PostQuery) WhereColumn(first any, args ...any) *PostQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *PostQuery) WhereKey(id any) *PostQuery {
	q.b.WhereKey(id)
	return q
}

func (q *PostQuery) WhereExists(callback func(*query.Builder)) *PostQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *PostQuery) WhereNotExists(callback func(*query.Builder)) *PostQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *PostQuery) WhereHas(relation string, callback func(*query.Builder)) *PostQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *PostQuery) OrWhereHas(relation string, callback func(*query.Builder)) *PostQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *PostQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *PostQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *PostQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *PostQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *PostQuery) WhereRelation(relation string, column any, args ...any) *PostQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *PostQuery) OrWhereRelation(relation string, column any, args ...any) *PostQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *PostQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *PostQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *PostQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *PostQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *PostQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *PostQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *PostQuery) OrHas(relation, operator string, count int) *PostQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *PostQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *PostQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *PostQuery) OrDoesntHave(relation string) *PostQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *PostQuery) Select(columns ...any) *PostQuery {
	q.b.Select(columns...)
	return q
}

func (q *PostQuery) AddSelect(columns ...any) *PostQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *PostQuery) SelectRaw(expression string, bindings ...any) *PostQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *PostQuery) Join(table any, first any, args ...any) *PostQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *PostQuery) GroupBy(groups ...any) *PostQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *PostQuery) OrderBy(column any, direction ...string) *PostQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *PostQuery) OrderByDesc(column any) *PostQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *PostQuery) Latest(column ...string) *PostQuery {
	q.b.Latest(column...)
	return q
}

func (q *PostQuery) Oldest(column ...string) *PostQuery {
	q.b.Oldest(column...)
	return q
}

func (q *PostQuery) Limit(value int) *PostQuery {
	q.b.Limit(value)
	return q
}

func (q *PostQuery) Offset(value int) *PostQuery {
	q.b.Offset(value)
	return q
}

func (q *PostQuery) ForPage(page, perPage int) *PostQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *PostQuery) With(relations ...string) *PostQuery {
	q.b.With(relations...)
	return q
}

func (q *PostQuery) WithCount(relations ...string) *PostQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *PostQuery) WithExists(relation string) *PostQuery {
	q.b.WithExists(relation)
	return q
}

func (q *PostQuery) WithSum(relation, column string) *PostQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *PostQuery) WithAvg(relation, column string) *PostQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *PostQuery) WithMin(relation, column string) *PostQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *PostQuery) WithMax(relation, column string) *PostQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *PostQuery) Without(relations ...string) *PostQuery {
	q.b.Without(relations...)
	return q
}

func (q *PostQuery) WithoutGlobalScope(identifier string) *PostQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *PostQuery) WithoutGlobalScopes(identifiers ...string) *PostQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *PostQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (PostCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return PostCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *PostQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Post, error) {
	e, err := q.b.First(ctx, g, columns...)
	return postOf(e), err
}

func (q *PostQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Post, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return postOf(e), err
}

func (q *PostQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Post, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return postOf(e), err
}

func (q *PostQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Post, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return postOf(e), err
}

func (q *PostQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Post, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return postOf(e), err
}

func (q *PostQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Post, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return postOf(e), err
}

func (q *PostQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Post, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return postOf(e), err
}

func (q *PostQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Post, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return postOf(e), err
}

func (q *PostQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (PostCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return PostCollectionOf(rows), err
}

func (q *PostQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Post, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return postOf(e), err
}

func (q *PostQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Post, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return postOf(e), err
}

func (q *PostQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Post, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return postOf(e), err
}

func (q *PostQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Post, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return postOf(e), err
}

func (q *PostQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (PostCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return PostCollectionOf(rows), meta, err
}

func (q *PostQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (PostCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return PostCollectionOf(rows), meta, err
}

func (q *PostQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (PostCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return PostCollectionOf(rows), meta, err
}

func (q *PostQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(PostCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(PostCollectionOf(rows), page)
	})
}

func (q *PostQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Post, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(postOf(e), index)
	})
}

func (q *PostQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Post, error] {
	return func(yield func(*Post, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(postOf(e), err) {
				return
			}
		}
	}
}

func (q *PostQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *PostQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *PostQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *PostQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *PostQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *PostQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *PostQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *PostQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *PostQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *PostQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *PostQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *PostQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *PostQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *PostQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *PostQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *PostQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *PostQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *PostQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *PostQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c PostCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c PostCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c PostCollection) Find(key any) *Post { return postOf(c.Rows().Find(key)) }

func (c PostCollection) FindOrFail(key any) (*Post, error) {
	e, err := c.Rows().FindOrFail(key)
	return postOf(e), err
}

func (c PostCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c PostCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c PostCollection) Only(keys ...any) PostCollection {
	return PostCollectionOf(c.Rows().Only(keys...))
}

func (c PostCollection) Except(keys ...any) PostCollection {
	return PostCollectionOf(c.Rows().Except(keys...))
}

func (c PostCollection) Unique() PostCollection { return PostCollectionOf(c.Rows().Unique()) }

func (c PostCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c PostCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c PostCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c PostCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (PostCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return PostCollectionOf(rows), err
}

func (c PostCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Post; it shadows the untyped one the
// embedded model promotes.
func (row *Post) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Post, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return postOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Post) Replicate(except ...string) (*Post, error) {
	e, err := row.Model.Replicate(except...)
	return postOf(e), err
}
