// Code generated by aru model:build from User.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Users starts a query on the table of User, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Users(db model.DB) *UserQuery { return &UserQuery{b: userTable.Query(db)} }

// UserQuery is a query on the table of User.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return User rows or a value; there is
// no way to run one without a Grant.
type UserQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of User.go -- and for the
// factory, which builds rows through it.
func (q *UserQuery) Base() *model.Builder { return q.b }

// New returns an empty User on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *UserQuery) New() (*User, error) {
	e, err := q.b.NewModelInstance(nil)
	return userOf(e), err
}

// UserCollection is rows of User, as a query returns them.
type UserCollection []*User

// UserCollectionOf converts rows of the table of User. A nil input is a nil
// collection.
func UserCollectionOf(rows model.Rows) UserCollection {
	if rows == nil {
		return nil
	}
	out := make(UserCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*User)
	}
	return out
}

func userOf(e model.Entity) *User {
	row, _ := e.(*User)
	return row
}

// userColumn turns a closure over UserQuery into one over the core builder, so
// passing func(*UserQuery) where a column goes adds a parenthesised group.
func userColumn(column any) any {
	if group, ok := column.(func(*UserQuery)); ok {
		return func(b *model.Builder) { group(&UserQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *UserQuery) Clone() *UserQuery { return &UserQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*UserQuery) in place of the column adds a group.
func (q *UserQuery) Where(column any, args ...any) *UserQuery {
	q.b.Where(userColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*UserQuery) in place of the column adds a group.
func (q *UserQuery) OrWhere(column any, args ...any) *UserQuery {
	q.b.OrWhere(userColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *UserQuery) WhereNot(column any, args ...any) *UserQuery {
	q.b.WhereNot(userColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *UserQuery) OrWhereNot(column any, args ...any) *UserQuery {
	q.b.OrWhereNot(userColumn(column), args...)
	return q
}

func (q *UserQuery) WhereIn(column any, values []any) *UserQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *UserQuery) WhereNotIn(column any, values []any) *UserQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *UserQuery) WhereNull(columns ...any) *UserQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *UserQuery) WhereNotNull(columns ...any) *UserQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *UserQuery) WhereBetween(column any, from, to any) *UserQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *UserQuery) WhereColumn(first any, args ...any) *UserQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *UserQuery) WhereKey(id any) *UserQuery {
	q.b.WhereKey(id)
	return q
}

func (q *UserQuery) WhereExists(callback func(*query.Builder)) *UserQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *UserQuery) WhereNotExists(callback func(*query.Builder)) *UserQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *UserQuery) WhereHas(relation string, callback func(*query.Builder)) *UserQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *UserQuery) OrWhereHas(relation string, callback func(*query.Builder)) *UserQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *UserQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *UserQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *UserQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *UserQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *UserQuery) WhereRelation(relation string, column any, args ...any) *UserQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *UserQuery) OrWhereRelation(relation string, column any, args ...any) *UserQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *UserQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *UserQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *UserQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *UserQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *UserQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *UserQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *UserQuery) OrHas(relation, operator string, count int) *UserQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *UserQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *UserQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *UserQuery) OrDoesntHave(relation string) *UserQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *UserQuery) Select(columns ...any) *UserQuery {
	q.b.Select(columns...)
	return q
}

func (q *UserQuery) AddSelect(columns ...any) *UserQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *UserQuery) SelectRaw(expression string, bindings ...any) *UserQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *UserQuery) Join(table any, first any, args ...any) *UserQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *UserQuery) GroupBy(groups ...any) *UserQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *UserQuery) OrderBy(column any, direction ...string) *UserQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *UserQuery) OrderByDesc(column any) *UserQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *UserQuery) Latest(column ...string) *UserQuery {
	q.b.Latest(column...)
	return q
}

func (q *UserQuery) Oldest(column ...string) *UserQuery {
	q.b.Oldest(column...)
	return q
}

func (q *UserQuery) Limit(value int) *UserQuery {
	q.b.Limit(value)
	return q
}

func (q *UserQuery) Offset(value int) *UserQuery {
	q.b.Offset(value)
	return q
}

func (q *UserQuery) ForPage(page, perPage int) *UserQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *UserQuery) With(relations ...string) *UserQuery {
	q.b.With(relations...)
	return q
}

func (q *UserQuery) WithCount(relations ...string) *UserQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *UserQuery) WithExists(relation string) *UserQuery {
	q.b.WithExists(relation)
	return q
}

func (q *UserQuery) WithSum(relation, column string) *UserQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *UserQuery) WithAvg(relation, column string) *UserQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *UserQuery) WithMin(relation, column string) *UserQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *UserQuery) WithMax(relation, column string) *UserQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *UserQuery) Without(relations ...string) *UserQuery {
	q.b.Without(relations...)
	return q
}

func (q *UserQuery) WithoutGlobalScope(identifier string) *UserQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *UserQuery) WithoutGlobalScopes(identifiers ...string) *UserQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *UserQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (UserCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return UserCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *UserQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*User, error) {
	e, err := q.b.First(ctx, g, columns...)
	return userOf(e), err
}

func (q *UserQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*User, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return userOf(e), err
}

func (q *UserQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*User, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return userOf(e), err
}

func (q *UserQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*User, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return userOf(e), err
}

func (q *UserQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*User, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return userOf(e), err
}

func (q *UserQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*User, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return userOf(e), err
}

func (q *UserQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*User, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return userOf(e), err
}

func (q *UserQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*User, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return userOf(e), err
}

func (q *UserQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (UserCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return UserCollectionOf(rows), err
}

func (q *UserQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*User, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return userOf(e), err
}

func (q *UserQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*User, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return userOf(e), err
}

func (q *UserQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*User, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return userOf(e), err
}

func (q *UserQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*User, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return userOf(e), err
}

func (q *UserQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (UserCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return UserCollectionOf(rows), meta, err
}

func (q *UserQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (UserCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return UserCollectionOf(rows), meta, err
}

func (q *UserQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (UserCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return UserCollectionOf(rows), meta, err
}

func (q *UserQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(UserCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(UserCollectionOf(rows), page)
	})
}

func (q *UserQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*User, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(userOf(e), index)
	})
}

func (q *UserQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*User, error] {
	return func(yield func(*User, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(userOf(e), err) {
				return
			}
		}
	}
}

func (q *UserQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *UserQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *UserQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *UserQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *UserQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *UserQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *UserQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *UserQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *UserQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *UserQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *UserQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *UserQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *UserQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *UserQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *UserQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *UserQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *UserQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *UserQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *UserQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c UserCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c UserCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c UserCollection) Find(key any) *User { return userOf(c.Rows().Find(key)) }

func (c UserCollection) FindOrFail(key any) (*User, error) {
	e, err := c.Rows().FindOrFail(key)
	return userOf(e), err
}

func (c UserCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c UserCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c UserCollection) Only(keys ...any) UserCollection {
	return UserCollectionOf(c.Rows().Only(keys...))
}

func (c UserCollection) Except(keys ...any) UserCollection {
	return UserCollectionOf(c.Rows().Except(keys...))
}

func (c UserCollection) Unique() UserCollection { return UserCollectionOf(c.Rows().Unique()) }

func (c UserCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c UserCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c UserCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c UserCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (UserCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return UserCollectionOf(rows), err
}

func (c UserCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new User; it shadows the untyped one the
// embedded model promotes.
func (row *User) Fresh(ctx context.Context, g auth.Grant, with ...string) (*User, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return userOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *User) Replicate(except ...string) (*User, error) {
	e, err := row.Model.Replicate(except...)
	return userOf(e), err
}
