// Code generated by `aru view:build` from app.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package layouts

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

func init() { view.RegisterLayout("layouts.app", renderLayoutsApp) }

// renderLayoutsApp renders the layouts.app layout.
func renderLayoutsApp(w io.Writer, data any, sections map[string]func(io.Writer) error) error {
	d, ok := data.(view.Layout)
	if !ok {
		return view.WrongData("layouts.app", "view.Layout", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<!doctype html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<html lang=\"en\" class=\"h-full\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta charset=\"utf-8\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<title>")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:12
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
//line resources/views/layouts/app.go:47
	}
	if err == nil {
		_, err = io.WriteString(w, "</title>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"icon\" href=\"/favicon.ico\">\n")
	}
//line resources/views/layouts/app.kyse.go:18
	if d.PageDescription() != "" {
//line resources/views/layouts/app.go:57
		if err == nil {
			_, err = io.WriteString(w, "\t\t<meta name=\"description\" content=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:19
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageDescription())))
//line resources/views/layouts/app.go:64
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t<meta property=\"og:description\" content=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:20
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageDescription())))
//line resources/views/layouts/app.go:75
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
	}
//line resources/views/layouts/app.kyse.go:22
	if d.CanonicalURL() != "" {
//line resources/views/layouts/app.go:83
		if err == nil {
			_, err = io.WriteString(w, "\t\t<link rel=\"canonical\" href=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:23
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CanonicalURL())))
//line resources/views/layouts/app.go:90
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t<meta property=\"og:url\" content=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:24
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CanonicalURL())))
//line resources/views/layouts/app.go:101
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:title\" content=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:26
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
//line resources/views/layouts/app.go:113
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:site_name\" content=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:27
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.BrandName())))
//line resources/views/layouts/app.go:124
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:type\" content=\"website\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"twitter:card\" content=\"summary_large_image\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:image\" content=\"/og-cover.svg\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"stylesheet\" href=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:34
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("app.css"))))
//line resources/views/layouts/app.go:144
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:35
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("htmx.min.js"))))
//line resources/views/layouts/app.go:155
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:36
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("alpine.min.js"))))
//line resources/views/layouts/app.go:166
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:37
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("basecoat.bundle.js"))))
//line resources/views/layouts/app.go:177
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:38
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("theme.js"))))
//line resources/views/layouts/app.go:188
	}
	if err == nil {
		_, err = io.WriteString(w, "\"></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<body hx-boost=\"true\" hx-headers='{\"X-CSRF-Token\": \"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:40
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CSRFToken())))
//line resources/views/layouts/app.go:202
	}
	if err == nil {
		_, err = io.WriteString(w, "\"}' class=\"bg-background text-foreground min-h-full antialiased\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div class=\"flex min-h-full flex-col\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<header class=\"border-b\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<nav class=\"mx-auto flex h-16 max-w-5xl items-center justify-between gap-4 px-6\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t<a href=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:44
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.HomeLink())))
//line resources/views/layouts/app.go:222
	}
	if err == nil {
		_, err = io.WriteString(w, "\" class=\"text-sm font-semibold tracking-tight\">")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:44
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.BrandName())))
//line resources/views/layouts/app.go:230
	}
	if err == nil {
		_, err = io.WriteString(w, "</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t<div class=\"flex items-center gap-2 text-sm\">\n")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:46
		_, err = io.WriteString(w, view.Text(components.ThemeToggle()))
//line resources/views/layouts/app.go:241
	}
//line resources/views/layouts/app.kyse.go:47
	if !d.SignedIn() {
//line resources/views/layouts/app.go:245
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t\t<a href=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:48
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginLink())))
//line resources/views/layouts/app.go:252
		}
		if err == nil {
			_, err = io.WriteString(w, "\" class=\"btn\" data-variant=\"ghost\" data-size=\"sm\">Login</a>\n")
		}
//line resources/views/layouts/app.kyse.go:49
		if d.RegisterLink() != "" {
//line resources/views/layouts/app.go:259
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t\t\t<a href=\"")
			}
			if err == nil {
//line resources/views/layouts/app.kyse.go:50
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RegisterLink())))
//line resources/views/layouts/app.go:266
			}
			if err == nil {
				_, err = io.WriteString(w, "\" class=\"btn\" data-size=\"sm\">Register</a>\n")
			}
		}
	}
//line resources/views/layouts/app.kyse.go:53
	if d.SignedIn() {
//line resources/views/layouts/app.go:275
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t\t<span class=\"text-muted-foreground\">")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:54
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.SignedInName())))
//line resources/views/layouts/app.go:282
		}
		if err == nil {
			_, err = io.WriteString(w, "</span>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t\t<form method=\"post\" action=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:55
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LogoutLink())))
//line resources/views/layouts/app.go:293
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			err = view.CSRF(w, data)
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\" data-variant=\"ghost\" data-size=\"sm\">Logout</button>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t\t</form>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t</nav>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</header>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<main class=\"mx-auto w-full max-w-5xl grow px-6 py-10\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "content")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</main>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<div id=\"toaster\" class=\"toaster\" aria-live=\"polite\"></div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</body>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</html>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
