package unit_test

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/arandu-io/examples/tests"
)

// There is one way the CSRF token reaches an HTMX request, and it is the
// hx-headers attribute on <body>. The layout the starter kit publishes carries it,
// the framework's own sign-in page carries it, and the error page names it by
// that string when a write is rejected.
//
// A resources/js/app.js attaching the same header from a htmx:configRequest
// listener would be a second answer to a question that already has one -- and,
// with nothing embedding it, nothing serving it and no layout referencing it, it
// would not even run. This test is what keeps one out.

// TestResourcesHoldNoJavaScript: resources/ is the input of `aru view:build`,
// and that build knows two kinds of file -- .kyse.go, which it compiles, and
// .css, which Tailwind reads. A .js in there is not built, not embedded and not
// served; it is a file that looks like behaviour and is not.
func TestResourcesHoldNoJavaScript(t *testing.T) {
	err := filepath.WalkDir(filepath.Join(tests.Root(t), "resources"), func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".js" {
			return nil
		}
		t.Errorf("%s is never built, embedded or served: `aru view:build` compiles .kyse.go and .css, "+
			"and the CSRF token travels in hx-headers on <body>", path)
		return nil
	})
	if err != nil {
		t.Fatalf("walking resources: %v", err)
	}
}

// TestOnlyTheLayoutsSetTheCSRFHeader is the same rule from inside the views. A
// control that writes its own hx-headers with the token in it is a second place
// the header is built by hand, and one that hides the layout's: hx-headers on
// an element replaces what it would have inherited for that key, so the two
// copies only agree for as long as nobody changes either.
func TestOnlyTheLayoutsSetTheCSRFHeader(t *testing.T) {
	root := filepath.Join(tests.Root(t), "resources", "views")
	layouts := map[string]bool{
		filepath.Join("layouts", "app.kyse.go"):  true,
		filepath.Join("admin", "layout.kyse.go"): true,
	}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".kyse.go") {
			return err
		}
		source, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		has := strings.Contains(string(source), "hx-headers=")
		switch {
		case layouts[rel] && !has:
			t.Errorf("resources/views/%s no longer sets hx-headers on <body>, and every htmx write under it would be refused", rel)
		case !layouts[rel] && has:
			t.Errorf("resources/views/%s sets hx-headers itself; the CSRF header comes from the layout's <body>", rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking resources/views: %v", err)
	}
}

// TestTheStylesheetDoesNotReadItsOwnOutput is the guard for a build that was
// not a function of its inputs.
//
// Tailwind v4 detects sources by itself on top of whatever @source declares,
// and the walk reaches assets/app.css -- the output of this very file. It read
// the class names back out of the previous build and fed them in again, so
// `aru view:build` twice in a row wrote two different stylesheets and a class
// removed from the last view that used it stayed in for one more build.
//
// source(none) turns the automatic half off and makes the @source lines the
// whole list. Every project generated by `aru new` clones this file, so the
// defect and the fix reach all of them.
func TestTheStylesheetDoesNotReadItsOwnOutput(t *testing.T) {
	source, err := os.ReadFile(filepath.Join(tests.Root(t), "resources", "css", "app.css"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(source), `@import "tailwindcss" source(none)`) {
		t.Error("resources/css/app.css lets Tailwind detect sources by itself: it will read assets/app.css, its own output")
	}
	if !strings.Contains(string(source), `@source "../views/`) {
		t.Error("with automatic detection off, the views have to be declared, or the stylesheet compiles to nothing")
	}
}

// Generated tooltip text cannot have descendants; its variants must not emit :has().
func TestCompiledStylesheetHasNoEmptyRelationalSelectors(t *testing.T) {
	source, err := os.ReadFile(filepath.Join(tests.Root(t), "assets", "app.css"))
	if err != nil {
		t.Fatal(err)
	}
	if len(source) == 0 {
		t.Fatal("the compiled stylesheet is empty")
	}
	if regexp.MustCompile(`:has\(\s*\)`).Match(source) {
		t.Fatal("the compiled stylesheet contains an empty relational selector")
	}
}

// releasedCLI is the aru release this tree is built and measured with.
const releasedCLI = "v0.67.0"

// Local, CI and image builds must use the same released view compiler, and
// the files that tell a reader which one this tree was measured with must name
// it too.
//
// Every occurrence is read, not just the first: a workflow that installs aru
// in two steps and was raised in one of them still contains the new version,
// and the step left behind builds the views with the old one.
func TestBuildEntrypointsUseTheReleasedCLI(t *testing.T) {
	root := tests.Root(t)
	installs := regexp.MustCompile(`github\.com/arandu-io/aru@(v[0-9][^\s` + "`" + `]*)`)
	for _, item := range []struct {
		path string
		pin  *regexp.Regexp
	}{
		{"arandu.toml", regexp.MustCompile(`(?m)^aru = "(v[^"]*)"`)},
		{"Dockerfile", regexp.MustCompile(`ARG ARU_VERSION=(v\S*)`)},
		{".github/workflows/ci.yml", installs},
		{"AGENTS.md", installs},
		{".agents/skills/examples-keep-it-true/SKILL.md", installs},
		{".agents/skills/examples-run-the-blog/SKILL.md", installs},
	} {
		body, err := os.ReadFile(filepath.Join(root, item.path))
		if err != nil {
			t.Fatal(err)
		}
		found := item.pin.FindAllSubmatch(body, -1)
		if len(found) == 0 {
			t.Errorf("%s names no aru release", item.path)
		}
		for _, match := range found {
			if string(match[1]) != releasedCLI {
				t.Errorf("%s uses aru %s, want %s", item.path, match[1], releasedCLI)
			}
		}
	}
}
