package unit_test

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arandu-io/examples/tests"
)

// There is one way the CSRF token reaches an HTMX request, and it is the
// hx-headers attribute on <body>. The layout the starter kit publishes carries it,
// the framework's own sign-in page carries it, and the error page names it by
// that string when a write is rejected.
//
// A resources/js/app.js attaching the same header from a htmx:configRequest
// listener would be a second answer to a question that already has one -- and,
// with nothing embedding it, nothing serving it and no layout referencing it, it
// would not even run. This test is what keeps one out.

// TestResourcesHoldNoJavaScript: resources/ is the input of `aru view:build`,
// and that build knows two kinds of file -- .kyse.go, which it compiles, and
// .css, which Tailwind reads. A .js in there is not built, not embedded and not
// served; it is a file that looks like behaviour and is not.
func TestResourcesHoldNoJavaScript(t *testing.T) {
	err := filepath.WalkDir(filepath.Join(tests.Root(t), "resources"), func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".js" {
			return nil
		}
		t.Errorf("%s is never built, embedded or served: `aru view:build` compiles .kyse.go and .css, "+
			"and the CSRF token travels in hx-headers on <body>", path)
		return nil
	})
	if err != nil {
		t.Fatalf("walking resources: %v", err)
	}
}

// TestTheStylesheetDoesNotReadItsOwnOutput is the guard for a build that was
// not a function of its inputs.
//
// Tailwind v4 detects sources by itself on top of whatever @source declares,
// and the walk reaches assets/app.css -- the output of this very file. It read
// the class names back out of the previous build and fed them in again, so
// `aru view:build` twice in a row wrote two different stylesheets and a class
// removed from the last view that used it stayed in for one more build.
//
// source(none) turns the automatic half off and makes the @source lines the
// whole list. Every project generated by `aru new` clones this file, so the
// defect and the fix reach all of them.
func TestTheStylesheetDoesNotReadItsOwnOutput(t *testing.T) {
	source, err := os.ReadFile(filepath.Join(tests.Root(t), "resources", "css", "app.css"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(source), `@import "tailwindcss" source(none)`) {
		t.Error("resources/css/app.css lets Tailwind detect sources by itself: it will read assets/app.css, its own output")
	}
	if !strings.Contains(string(source), `@source "../views/`) {
		t.Error("with automatic detection off, the views have to be declared, or the stylesheet compiles to nothing")
	}
}
